if exist "..\32_0.gif" ren "..\32_0.gif" "Aht Urhgan Whitegate.gif"
if exist "..\e0_0.gif" ren "..\e0_0.gif" "Airship - Jeuno-Bastok.gif"
if exist "..\e2_0.gif" ren "..\e2_0.gif" "Airship - Jeuno-Kazham.gif"
if exist "..\df_0.gif" ren "..\df_0.gif" "Airship - Jeuno-SandOria.gif"
if exist "..\e1_0.gif" ren "..\e1_0.gif" "Airship - Jeuno-Windurst.gif"
if exist "..\d6_0.gif" ren "..\d6_0.gif" "Al Zhabi Residential Area.gif"
if exist "..\30_0.gif" ren "..\30_0.gif" "Al Zhabi.gif"
if exist "..\21_0.gif" ren "..\21_0.gif" "Al'Taieu.gif"
if exist "..\98_0.gif" ren "..\98_0.gif" "Altar Room.gif"
if exist "..\48_0.gif" ren "..\48_0.gif" "Alzadaal Undersea Ruins 1.gif"
if exist "..\48_9.gif" ren "..\48_9.gif" "Alzadaal Undersea Ruins 10.gif"
if exist "..\48_10.gif" ren "..\48_10.gif" "Alzadaal Undersea Ruins 11.gif"
if exist "..\48_11.gif" ren "..\48_11.gif" "Alzadaal Undersea Ruins 12.gif"
if exist "..\48_1.gif" ren "..\48_1.gif" "Alzadaal Undersea Ruins 2.gif"
if exist "..\48_2.gif" ren "..\48_2.gif" "Alzadaal Undersea Ruins 3.gif"
if exist "..\48_3.gif" ren "..\48_3.gif" "Alzadaal Undersea Ruins 4.gif"
if exist "..\48_4.gif" ren "..\48_4.gif" "Alzadaal Undersea Ruins 5.gif"
if exist "..\48_5.gif" ren "..\48_5.gif" "Alzadaal Undersea Ruins 6.gif"
if exist "..\48_6.gif" ren "..\48_6.gif" "Alzadaal Undersea Ruins 7.gif"
if exist "..\48_7.gif" ren "..\48_7.gif" "Alzadaal Undersea Ruins 8.gif"
if exist "..\48_8.gif" ren "..\48_8.gif" "Alzadaal Undersea Ruins 9.gif"
if exist "..\26_6.gif" ren "..\26_6.gif" "Apollyon-CN.gif"
if exist "..\26_7.gif" ren "..\26_7.gif" "Apollyon-CS.gif"
if exist "..\26_0.gif" ren "..\26_0.gif" "Apollyon-Entrance-SE.gif"
if exist "..\26_1.gif" ren "..\26_1.gif" "Apollyon-Entrance-SW.gif"
if exist "..\26_2.gif" ren "..\26_2.gif" "Apollyon-NE.gif"
if exist "..\26_3.gif" ren "..\26_3.gif" "Apollyon-NW.gif"
if exist "..\26_4.gif" ren "..\26_4.gif" "Apollyon-SE.gif"
if exist "..\26_5.gif" ren "..\26_5.gif" "Apollyon-SW.gif"
if exist "..\36_0.gif" ren "..\36_0.gif" "Arrapago Reef 1.gif"
if exist "..\36_9.gif" ren "..\36_9.gif" "Arrapago Reef 10.gif"
if exist "..\36_10.gif" ren "..\36_10.gif" "Arrapago Reef 11.gif"
if exist "..\36_1.gif" ren "..\36_1.gif" "Arrapago Reef 2.gif"
if exist "..\36_2.gif" ren "..\36_2.gif" "Arrapago Reef 3.gif"
if exist "..\36_3.gif" ren "..\36_3.gif" "Arrapago Reef 4.gif"
if exist "..\36_4.gif" ren "..\36_4.gif" "Arrapago Reef 5.gif"
if exist "..\36_5.gif" ren "..\36_5.gif" "Arrapago Reef 6.gif"
if exist "..\36_6.gif" ren "..\36_6.gif" "Arrapago Reef 7.gif"
if exist "..\36_7.gif" ren "..\36_7.gif" "Arrapago Reef 8.gif"
if exist "..\36_8.gif" ren "..\36_8.gif" "Arrapago Reef 9.gif"
if exist "..\4a_0.gif" ren "..\4a_0.gif" "Arrapago Remnants 1.gif"
if exist "..\4a_1.gif" ren "..\4a_1.gif" "Arrapago Remnants 2.gif"
if exist "..\4a_2.gif" ren "..\4a_2.gif" "Arrapago Remnants 3.gif"
if exist "..\4a_3.gif" ren "..\4a_3.gif" "Arrapago Remnants 4.gif"
if exist "..\4a_4.gif" ren "..\4a_4.gif" "Arrapago Remnants 5.gif"
if exist "..\4a_5.gif" ren "..\4a_5.gif" "Arrapago Remnants 6.gif"
if exist "..\4a_6.gif" ren "..\4a_6.gif" "Arrapago Remnants 7.gif"
if exist "..\07_0.gif" ren "..\07_0.gif" "Attohwa Chasm.gif"
if exist "..\44_0.gif" ren "..\44_0.gif" "Aydeewa Subterrane 1.gif"
if exist "..\44_1.gif" ren "..\44_1.gif" "Aydeewa Subterrane 2.gif"
if exist "..\44_2.gif" ren "..\44_2.gif" "Aydeewa Subterrane 3.gif"
if exist "..\44_3.gif" ren "..\44_3.gif" "Aydeewa Subterrane 4.gif"
if exist "..\44_4.gif" ren "..\44_4.gif" "Aydeewa Subterrane 5.gif"
if exist "..\44_5.gif" ren "..\44_5.gif" "Aydeewa Subterrane 6.gif"
if exist "..\44_6.gif" ren "..\44_6.gif" "Aydeewa Subterrane 7.gif"
if exist "..\92_0.gif" ren "..\92_0.gif" "Balga's Dais.gif"
if exist "..\57_0.gif" ren "..\57_0.gif" "Bastok Markets [S].gif"
if exist "..\eb_0.gif" ren "..\eb_0.gif" "Bastok Markets.gif"
if exist "..\ea_0.gif" ren "..\ea_0.gif" "Bastok Mines.gif"
if exist "..\d9_0.gif" ren "..\d9_0.gif" "Bastok Residential Area.gif"
if exist "..\54_0.gif" ren "..\54_0.gif" "Batallia Downs [S].gif"
if exist "..\69_0.gif" ren "..\69_0.gif" "Batallia Downs.gif"
if exist "..\5c_0.gif" ren "..\5c_0.gif" "Beadeaux 1 [S].gif"
if exist "..\93_0.gif" ren "..\93_0.gif" "Beadeaux 1.gif"
if exist "..\5c_1.gif" ren "..\5c_1.gif" "Beadeaux 2 [S].gif"
if exist "..\93_1.gif" ren "..\93_1.gif" "Beadeaux 2.gif"
if exist "..\88_0.gif" ren "..\88_0.gif" "Beaucedine Glacier [S].gif"
if exist "..\6f_0.gif" ren "..\6f_0.gif" "Beaucedine Glacier.gif"
if exist "..\7f_0.gif" ren "..\7f_0.gif" "Behemoth's Dominion.gif"
if exist "..\4b_0.gif" ren "..\4b_0.gif" "Bhaflau Remnants 1.gif"
if exist "..\4b_1.gif" ren "..\4b_1.gif" "Bhaflau Remnants 2.gif"
if exist "..\4b_2.gif" ren "..\4b_2.gif" "Bhaflau Remnants 3.gif"
if exist "..\4b_3.gif" ren "..\4b_3.gif" "Bhaflau Remnants 4.gif"
if exist "..\4b_4.gif" ren "..\4b_4.gif" "Bhaflau Remnants 5.gif"
if exist "..\34_0.gif" ren "..\34_0.gif" "Bhaflau Thickets 1.gif"
if exist "..\34_1.gif" ren "..\34_1.gif" "Bhaflau Thickets 2.gif"
if exist "..\04_0.gif" ren "..\04_0.gif" "Bibiki Bay.gif"
if exist "..\08_0.gif" ren "..\08_0.gif" "Boneyard Gully.gif"
if exist "..\a7_0.gif" ren "..\a7_0.gif" "Bostaunieux Oubliette 1.gif"
if exist "..\a7_1.gif" ren "..\a7_1.gif" "Bostaunieux Oubliette 2.gif"
if exist "..\a7_2.gif" ren "..\a7_2.gif" "Bostaunieux Oubliette 3.gif"
if exist "..\76_0.gif" ren "..\76_0.gif" "Buburimu Peninsula.gif"
if exist "..\4f_0.gif" ren "..\4f_0.gif" "Caedarva Mire 1.gif"
if exist "..\4f_1.gif" ren "..\4f_1.gif" "Caedarva Mire 2.gif"
if exist "..\4f_2.gif" ren "..\4f_2.gif" "Caedarva Mire 3.gif"
if exist "..\4f_3.gif" ren "..\4f_3.gif" "Caedarva Mire 4.gif"
if exist "..\71_0.gif" ren "..\71_0.gif" "Cape Teriggan.gif"
if exist "..\02_0.gif" ren "..\02_0.gif" "Carpenters' Landing 1.gif"
if exist "..\02_1.gif" ren "..\02_1.gif" "Carpenters' Landing 2.gif"
if exist "..\63_0.gif" ren "..\63_0.gif" "Castle Oztroja 1 [S].gif"
if exist "..\97_0.gif" ren "..\97_0.gif" "Castle Oztroja 1.gif"
if exist "..\63_1.gif" ren "..\63_1.gif" "Castle Oztroja 2 [S].gif"
if exist "..\97_1.gif" ren "..\97_1.gif" "Castle Oztroja 2.gif"
if exist "..\63_2.gif" ren "..\63_2.gif" "Castle Oztroja 3 [S].gif"
if exist "..\97_2.gif" ren "..\97_2.gif" "Castle Oztroja 3.gif"
if exist "..\63_3.gif" ren "..\63_3.gif" "Castle Oztroja 4 [S].gif"
if exist "..\97_3.gif" ren "..\97_3.gif" "Castle Oztroja 4.gif"
if exist "..\63_4.gif" ren "..\63_4.gif" "Castle Oztroja 5 [S].gif"
if exist "..\97_4.gif" ren "..\97_4.gif" "Castle Oztroja 5.gif"
if exist "..\63_5.gif" ren "..\63_5.gif" "Castle Oztroja 6 [S].gif"
if exist "..\97_5.gif" ren "..\97_5.gif" "Castle Oztroja 6.gif"
if exist "..\97_6.gif" ren "..\97_6.gif" "Castle Oztroja 7.gif"
if exist "..\8a_0.gif" ren "..\8a_0.gif" "Castle Zvahl Baileys 1 [S].gif"
if exist "..\a1_0.gif" ren "..\a1_0.gif" "Castle Zvahl Baileys 1.gif"
if exist "..\8a_1.gif" ren "..\8a_1.gif" "Castle Zvahl Baileys 2 [S].gif"
if exist "..\a1_1.gif" ren "..\a1_1.gif" "Castle Zvahl Baileys 2.gif"
if exist "..\8a_2.gif" ren "..\8a_2.gif" "Castle Zvahl Baileys 3 [S].gif"
if exist "..\a1_2.gif" ren "..\a1_2.gif" "Castle Zvahl Baileys 3.gif"
if exist "..\8a_3.gif" ren "..\8a_3.gif" "Castle Zvahl Baileys 4 [S].gif"
if exist "..\a1_3.gif" ren "..\a1_3.gif" "Castle Zvahl Baileys 4.gif"
if exist "..\9b_0.gif" ren "..\9b_0.gif" "Castle Zvahl Keep 1 [S].gif"
if exist "..\a2_0.gif" ren "..\a2_0.gif" "Castle Zvahl Keep 1.gif"
if exist "..\9b_1.gif" ren "..\9b_1.gif" "Castle Zvahl Keep 2 [S].gif"
if exist "..\a2_1.gif" ren "..\a2_1.gif" "Castle Zvahl Keep 2.gif"
if exist "..\9b_2.gif" ren "..\9b_2.gif" "Castle Zvahl Keep 3 [S].gif"
if exist "..\a2_2.gif" ren "..\a2_2.gif" "Castle Zvahl Keep 3.gif"
if exist "..\9b_3.gif" ren "..\9b_3.gif" "Castle Zvahl Keep 4 [S].gif"
if exist "..\a2_3.gif" ren "..\a2_3.gif" "Castle Zvahl Keep 4.gif"
if exist "..\a8_0.gif" ren "..\a8_0.gif" "Chamber of Oracles.gif"
if exist "..\e9_0.gif" ren "..\e9_0.gif" "Chateau d'Oraguille.gif"
if exist "..\46_0.gif" ren "..\46_0.gif" "Chocobo Circuit 1.gif"
if exist "..\46_1.gif" ren "..\46_1.gif" "Chocobo Circuit 2.gif"
if exist "..\46_2.gif" ren "..\46_2.gif" "Chocobo Circuit 3.gif"
if exist "..\46_3.gif" ren "..\46_3.gif" "Chocobo Circuit 4.gif"
if exist "..\46_4.gif" ren "..\46_4.gif" "Chocobo Circuit 5.gif"
if exist "..\46_5.gif" ren "..\46_5.gif" "Chocobo Circuit 6.gif"
if exist "..\46_6.gif" ren "..\46_6.gif" "Chocobo Circuit 7.gif"
if exist "..\cf_0.gif" ren "..\cf_0.gif" "Cloister of Flames.gif"
if exist "..\cb_0.gif" ren "..\cb_0.gif" "Cloister of Frost.gif"
if exist "..\c9_0.gif" ren "..\c9_0.gif" "Cloister of Gales.gif"
if exist "..\ca_0.gif" ren "..\ca_0.gif" "Cloister of Storms.gif"
if exist "..\d3_0.gif" ren "..\d3_0.gif" "Cloister of Tides.gif"
if exist "..\d1_0.gif" ren "..\d1_0.gif" "Cloister of Tremors.gif"
if exist "..\ab_0.gif" ren "..\ab_0.gif" "Crawlers Nest 1 [S].gif"
if exist "..\c5_0.gif" ren "..\c5_0.gif" "Crawlers' Nest 1.gif"
if exist "..\ab_1.gif" ren "..\ab_1.gif" "Crawlers Nest 2 [S].gif"
if exist "..\c5_1.gif" ren "..\c5_1.gif" "Crawlers' Nest 2.gif"
if exist "..\c5_2.gif" ren "..\c5_2.gif" "Crawlers' Nest 3.gif"
if exist "..\c5_3.gif" ren "..\c5_3.gif" "Crawlers' Nest Unknown.gif"
if exist "..\bf_0.gif" ren "..\bf_0.gif" "Dangruf Wadi a.gif"
if exist "..\bf_1.gif" ren "..\bf_1.gif" "Dangruf Wadi b.gif"
if exist "..\55_0.gif" ren "..\55_0.gif" "Davoi [S].gif"
if exist "..\95_0.gif" ren "..\95_0.gif" "Davoi.gif"
if exist "..\b8_3.gif" ren "..\b8_3.gif" "Delkfutt's Tower 0.gif"
if exist "..\b8_0.gif" ren "..\b8_0.gif" "Delkfutt's Tower 1.gif"
if exist "..\9e_0.gif" ren "..\9e_0.gif" "Delkfutt's Tower 10.gif"
if exist "..\9e_1.gif" ren "..\9e_1.gif" "Delkfutt's Tower 11.gif"
if exist "..\9e_2.gif" ren "..\9e_2.gif" "Delkfutt's Tower 12.gif"
if exist "..\9e_3.gif" ren "..\9e_3.gif" "Delkfutt's Tower 13.gif"
if exist "..\9e_4.gif" ren "..\9e_4.gif" "Delkfutt's Tower 14.gif"
if exist "..\9e_5.gif" ren "..\9e_5.gif" "Delkfutt's Tower 15.gif"
if exist "..\b8_1.gif" ren "..\b8_1.gif" "Delkfutt's Tower 2.gif"
if exist "..\b8_2.gif" ren "..\b8_2.gif" "Delkfutt's Tower 3.gif"
if exist "..\9d_0.gif" ren "..\9d_0.gif" "Delkfutt's Tower 4.gif"
if exist "..\9d_1.gif" ren "..\9d_1.gif" "Delkfutt's Tower 5.gif"
if exist "..\9d_2.gif" ren "..\9d_2.gif" "Delkfutt's Tower 6.gif"
if exist "..\9d_3.gif" ren "..\9d_3.gif" "Delkfutt's Tower 7.gif"
if exist "..\9d_4.gif" ren "..\9d_4.gif" "Delkfutt's Tower 8.gif"
if exist "..\9d_5.gif" ren "..\9d_5.gif" "Delkfutt's Tower 9.gif"
if exist "..\a0_0.gif" ren "..\a0_0.gif" "Den of Rancor 1.gif"
if exist "..\a0_1.gif" ren "..\a0_1.gif" "Den of Rancor 2.gif"
if exist "..\a0_2.gif" ren "..\a0_2.gif" "Den of Rancor 3.gif"
if exist "..\a0_3.gif" ren "..\a0_3.gif" "Den of Rancor 4.gif"
if exist "..\a0_4.gif" ren "..\a0_4.gif" "Den of Rancor 5.gif"
if exist "..\a0_5.gif" ren "..\a0_5.gif" "Den of Rancor 6.gif"
if exist "..\a0_6.gif" ren "..\a0_6.gif" "Den of Rancor 7.gif"
if exist "..\a0_7.gif" ren "..\a0_7.gif" "Den of Rancor 8.gif"
if exist "..\a0_8.gif" ren "..\a0_8.gif" "Den of Rancor 9.gif"
if exist "..\2b_0.gif" ren "..\2b_0.gif" "Diorama Abdhaljs-Ghelsba.gif"
if exist "..\2c_0.gif" ren "..\2c_0.gif" "Diorama Abdhaljs-Purgonorgo Isle.gif"
if exist "..\9a_0.gif" ren "..\9a_0.gif" "Dragon's Aery.gif"
if exist "..\ba_0.gif" ren "..\ba_0.gif" "Dynamis - Bastok.gif"
if exist "..\86_0.gif" ren "..\86_0.gif" "Dynamis - Beaucedine.gif"
if exist "..\28_0.gif" ren "..\28_0.gif" "Dynamis - Buburimu.gif"
if exist "..\bc_0.gif" ren "..\bc_0.gif" "Dynamis - Jeuno.gif"
if exist "..\29_0.gif" ren "..\29_0.gif" "Dynamis - Qufim.gif"
if exist "..\b9_0.gif" ren "..\b9_0.gif" "Dynamis - San d'Oria.gif"
if exist "..\2a_0.gif" ren "..\2a_0.gif" "Dynamis - Tavnazia 1.gif"
if exist "..\2a_1.gif" ren "..\2a_1.gif" "Dynamis - Tavnazia 2.gif"
if exist "..\2a_2.gif" ren "..\2a_2.gif" "Dynamis - Tavnazia 3.gif"
if exist "..\27_0.gif" ren "..\27_0.gif" "Dynamis - Valkurm.gif"
if exist "..\bb_0.gif" ren "..\bb_0.gif" "Dynamis - Windurst.gif"
if exist "..\87_0.gif" ren "..\87_0.gif" "Dynamis - Xarcabard.gif"
if exist "..\51_0.gif" ren "..\51_0.gif" "East Ronfaure [S].gif"
if exist "..\65_0.gif" ren "..\65_0.gif" "East Ronfaure.gif"
if exist "..\74_0.gif" ren "..\74_0.gif" "East Sarutabaruta.gif"
if exist "..\72_0.gif" ren "..\72_0.gif" "Eastern Altepa Desert.gif"
if exist "..\af_0.gif" ren "..\af_0.gif" "Eldieme Necropolis 1 [S].gif"
if exist "..\af_1.gif" ren "..\af_1.gif" "Eldieme Necropolis 2 [S].gif"
if exist "..\af_2.gif" ren "..\af_2.gif" "Eldieme Necropolis 3 [S].gif"
if exist "..\24_0.gif" ren "..\24_0.gif" "Empyreal Paradox.gif"
if exist "..\56_0.gif" ren "..\56_0.gif" "Everbloom Hollow 1.gif"
if exist "..\56_9.gif" ren "..\56_9.gif" "Everbloom Hollow 10.gif"
if exist "..\56_10.gif" ren "..\56_10.gif" "Everbloom Hollow 11.gif"
if exist "..\56_11.gif" ren "..\56_11.gif" "Everbloom Hollow 12.gif"
if exist "..\56_12.gif" ren "..\56_12.gif" "Everbloom Hollow 13.gif"
if exist "..\56_13.gif" ren "..\56_13.gif" "Everbloom Hollow 14.gif"
if exist "..\56_14.gif" ren "..\56_14.gif" "Everbloom Hollow 15.gif"
if exist "..\56_15.gif" ren "..\56_15.gif" "Everbloom Hollow 16.gif"
if exist "..\56_16.gif" ren "..\56_16.gif" "Everbloom Hollow 17.gif"
if exist "..\56_17.gif" ren "..\56_17.gif" "Everbloom Hollow 18.gif"
if exist "..\56_1.gif" ren "..\56_1.gif" "Everbloom Hollow 2.gif"
if exist "..\56_2.gif" ren "..\56_2.gif" "Everbloom Hollow 3.gif"
if exist "..\56_3.gif" ren "..\56_3.gif" "Everbloom Hollow 4.gif"
if exist "..\56_4.gif" ren "..\56_4.gif" "Everbloom Hollow 5.gif"
if exist "..\56_5.gif" ren "..\56_5.gif" "Everbloom Hollow 6.gif"
if exist "..\56_6.gif" ren "..\56_6.gif" "Everbloom Hollow 7.gif"
if exist "..\56_7.gif" ren "..\56_7.gif" "Everbloom Hollow 8.gif"
if exist "..\56_8.gif" ren "..\56_8.gif" "Everbloom Hollow 9.gif"
if exist "..\cc_0.gif" ren "..\cc_0.gif" "Fei'Yin 1.gif"
if exist "..\cc_1.gif" ren "..\cc_1.gif" "Fei'Yin 2.gif"
if exist "..\2e_0.gif" ren "..\2e_0.gif" "Ferry - Mhaura-AlZahbi 1.gif"
if exist "..\2f_0.gif" ren "..\2f_0.gif" "Ferry - Mhaura-AlZahbi 2.gif"
if exist "..\3a_0.gif" ren "..\3a_0.gif" "Ferry - Nashmau-AlZahbi 1.gif"
if exist "..\3b_0.gif" ren "..\3b_0.gif" "Ferry - Nashmau-AlZahbi 2.gif"
if exist "..\dc_0.gif" ren "..\dc_0.gif" "Ferry - Selbina-Mhaura 1.gif"
if exist "..\e3_0.gif" ren "..\e3_0.gif" "Ferry - Selbina-Mhaura 2.gif"
if exist "..\dd_0.gif" ren "..\dd_0.gif" "Ferry - Selbina-Mhaura 3.gif"
if exist "..\e4_0.gif" ren "..\e4_0.gif" "Ferry - Selbina-Mhaura 4.gif"
if exist "..\8d_0.gif" ren "..\8d_0.gif" "Fort Ghelsba.gif"
if exist "..\60_0.gif" ren "..\60_0.gif" "Fort Karugo-Narugo 1.gif"
if exist "..\60_1.gif" ren "..\60_1.gif" "Fort Karugo-Narugo 2.gif"
if exist "..\aa_0.gif" ren "..\aa_0.gif" "Full Moon Fountain.gif"
if exist "..\a4_0.gif" ren "..\a4_0.gif" "Garlaige Citadel 1 [S].gif"
if exist "..\c8_0.gif" ren "..\c8_0.gif" "Garlaige Citadel 1.gif"
if exist "..\a4_1.gif" ren "..\a4_1.gif" "Garlaige Citadel 2 [S].gif"
if exist "..\c8_1.gif" ren "..\c8_1.gif" "Garlaige Citadel 2.gif"
if exist "..\a4_2.gif" ren "..\a4_2.gif" "Garlaige Citadel 3 [S].gif"
if exist "..\c8_2.gif" ren "..\c8_2.gif" "Garlaige Citadel 3.gif"
if exist "..\a4_3.gif" ren "..\a4_3.gif" "Garlaige Citadel 4 [S].gif"
if exist "..\c8_3.gif" ren "..\c8_3.gif" "Garlaige Citadel 4.gif"
if exist "..\8c_0.gif" ren "..\8c_0.gif" "Ghelsba Outpost 1.gif"
if exist "..\8c_1.gif" ren "..\8c_1.gif" "Ghelsba Outpost 2.gif"
if exist "..\81_0.gif" ren "..\81_0.gif" "Ghoyus Reverie 1.gif"
if exist "..\81_9.gif" ren "..\81_9.gif" "Ghoyus Reverie 10.gif"
if exist "..\81_10.gif" ren "..\81_10.gif" "Ghoyus Reverie 11.gif"
if exist "..\81_11.gif" ren "..\81_11.gif" "Ghoyus Reverie 12.gif"
if exist "..\81_12.gif" ren "..\81_12.gif" "Ghoyus Reverie 13.gif"
if exist "..\81_13.gif" ren "..\81_13.gif" "Ghoyus Reverie 14.gif"
if exist "..\81_14.gif" ren "..\81_14.gif" "Ghoyus Reverie 15.gif"
if exist "..\81_15.gif" ren "..\81_15.gif" "Ghoyus Reverie 16.gif"
if exist "..\81_16.gif" ren "..\81_16.gif" "Ghoyus Reverie 17.gif"
if exist "..\81_17.gif" ren "..\81_17.gif" "Ghoyus Reverie 18.gif"
if exist "..\81_1.gif" ren "..\81_1.gif" "Ghoyus Reverie 2.gif"
if exist "..\81_2.gif" ren "..\81_2.gif" "Ghoyus Reverie 3.gif"
if exist "..\81_3.gif" ren "..\81_3.gif" "Ghoyus Reverie 4.gif"
if exist "..\81_4.gif" ren "..\81_4.gif" "Ghoyus Reverie 5.gif"
if exist "..\81_5.gif" ren "..\81_5.gif" "Ghoyus Reverie 6.gif"
if exist "..\81_6.gif" ren "..\81_6.gif" "Ghoyus Reverie 7.gif"
if exist "..\81_7.gif" ren "..\81_7.gif" "Ghoyus Reverie 8.gif"
if exist "..\81_8.gif" ren "..\81_8.gif" "Ghoyus Reverie 9.gif"
if exist "..\91_0.gif" ren "..\91_0.gif" "Giddeus 1.gif"
if exist "..\91_1.gif" ren "..\91_1.gif" "Giddeus 2.gif"
if exist "..\22_0.gif" ren "..\22_0.gif" "Grand Palace of Hu'Xzoi 1.gif"
if exist "..\22_1.gif" ren "..\22_1.gif" "Grand Palace of Hu'Xzoi 2.gif"
if exist "..\22_2.gif" ren "..\22_2.gif" "Grand Palace of Hu'Xzoi 3.gif"
if exist "..\59_0.gif" ren "..\59_0.gif" "Grauberg.gif"
if exist "..\c4_0.gif" ren "..\c4_0.gif" "Gusgen Mines 1.gif"
if exist "..\c4_1.gif" ren "..\c4_1.gif" "Gusgen Mines 2 a.gif"
if exist "..\c4_4.gif" ren "..\c4_4.gif" "Gusgen Mines 2 b.gif"
if exist "..\c4_2.gif" ren "..\c4_2.gif" "Gusgen Mines 3.gif"
if exist "..\c4_3.gif" ren "..\c4_3.gif" "Gusgen Mines 4.gif"
if exist "..\d4_0.gif" ren "..\d4_0.gif" "Gustav Tunnel 1.gif"
if exist "..\d4_1.gif" ren "..\d4_1.gif" "Gustav Tunnel 2.gif"
if exist "..\fb_0.gif" ren "..\fb_0.gif" "Hall of the Gods.gif"
if exist "..\0e_0.gif" ren "..\0e_0.gif" "Hall of Transference 1.gif"
if exist "..\0e_1.gif" ren "..\0e_1.gif" "Hall of Transference 2.gif"
if exist "..\0e_2.gif" ren "..\0e_2.gif" "Hall of Transference 3.gif"
if exist "..\3e_0.gif" ren "..\3e_0.gif" "Halvung 1.gif"
if exist "..\3e_1.gif" ren "..\3e_1.gif" "Halvung 2.gif"
if exist "..\3e_2.gif" ren "..\3e_2.gif" "Halvung 3.gif"
if exist "..\3e_3.gif" ren "..\3e_3.gif" "Halvung 4.gif"
if exist "..\f2_0.gif" ren "..\f2_0.gif" "Heavens Tower 1.gif"
if exist "..\f2_1.gif" ren "..\f2_1.gif" "Heavens Tower 2.gif"
if exist "..\f2_2.gif" ren "..\f2_2.gif" "Heavens Tower 3.gif"
if exist "..\f2_3.gif" ren "..\f2_3.gif" "Heavens Tower 4.gif"
if exist "..\8b_0.gif" ren "..\8b_0.gif" "Horlais Peak.gif"
if exist "..\c0_0.gif" ren "..\c0_0.gif" "Horutoto Ruins 1.gif"
if exist "..\c0_1.gif" ren "..\c0_1.gif" "Horutoto Ruins 2.gif"
if exist "..\c0_2.gif" ren "..\c0_2.gif" "Horutoto Ruins 3.gif"
if exist "..\c0_3.gif" ren "..\c0_3.gif" "Horutoto Ruins 4.gif"
if exist "..\c2_0.gif" ren "..\c2_0.gif" "Horutoto Ruins 5.gif"
if exist "..\c2_1.gif" ren "..\c2_1.gif" "Horutoto Ruins 6.gif"
if exist "..\c2_2.gif" ren "..\c2_2.gif" "Horutoto Ruins 7.gif"
if exist "..\c2_3.gif" ren "..\c2_3.gif" "Horutoto Ruins 8.gif"
if exist "..\c2_4.gif" ren "..\c2_4.gif" "Horutoto Ruins 9 a.gif"
if exist "..\c2_5.gif" ren "..\c2_5.gif" "Horutoto Ruins 9 b.gif"
if exist "..\cd_0.gif" ren "..\cd_0.gif" "Ifrit's Cauldron 1.gif"
if exist "..\cd_1.gif" ren "..\cd_1.gif" "Ifrit's Cauldron 2.gif"
if exist "..\cd_2.gif" ren "..\cd_2.gif" "Ifrit's Cauldron 3.gif"
if exist "..\cd_3.gif" ren "..\cd_3.gif" "Ifrit's Cauldron 4.gif"
if exist "..\cd_4.gif" ren "..\cd_4.gif" "Ifrit's Cauldron 5.gif"
if exist "..\cd_5.gif" ren "..\cd_5.gif" "Ifrit's Cauldron 6.gif"
if exist "..\cd_6.gif" ren "..\cd_6.gif" "Ifrit's Cauldron 7.gif"
if exist "..\cd_7.gif" ren "..\cd_7.gif" "Ifrit's Cauldron 8.gif"
if exist "..\37_0.gif" ren "..\37_0.gif" "Ilrusi Atoll 1.gif"
if exist "..\37_9.gif" ren "..\37_9.gif" "Ilrusi Atoll 10.gif"
if exist "..\37_1.gif" ren "..\37_1.gif" "Ilrusi Atoll 2.gif"
if exist "..\37_2.gif" ren "..\37_2.gif" "Ilrusi Atoll 3.gif"
if exist "..\37_3.gif" ren "..\37_3.gif" "Ilrusi Atoll 4.gif"
if exist "..\37_4.gif" ren "..\37_4.gif" "Ilrusi Atoll 5.gif"
if exist "..\37_5.gif" ren "..\37_5.gif" "Ilrusi Atoll 6.gif"
if exist "..\37_6.gif" ren "..\37_6.gif" "Ilrusi Atoll 7.gif"
if exist "..\37_7.gif" ren "..\37_7.gif" "Ilrusi Atoll 8.gif"
if exist "..\37_8.gif" ren "..\37_8.gif" "Ilrusi Atoll 9.gif"
if exist "..\43_0.gif" ren "..\43_0.gif" "Jade Sepulcher.gif"
if exist "..\d7_0.gif" ren "..\d7_0.gif" "Jeuno Residential Area.gif"
if exist "..\52_0.gif" ren "..\52_0.gif" "Jugner Forest [S].gif"
if exist "..\68_0.gif" ren "..\68_0.gif" "Jugner Forest.gif"
if exist "..\fa_0.gif" ren "..\fa_0.gif" "Kazham.gif"
if exist "..\be_0.gif" ren "..\be_0.gif" "King Ranperre's Tomb 1.gif"
if exist "..\be_1.gif" ren "..\be_1.gif" "King Ranperre's Tomb 2.gif"
if exist "..\0f_0.gif" ren "..\0f_0.gif" "Konschtat Highlands [A].gif"
if exist "..\6c_0.gif" ren "..\6c_0.gif" "Konschtat Highlands.gif"
if exist "..\ad_0.gif" ren "..\ad_0.gif" "Korroloka Tunnel 1.gif"
if exist "..\ad_1.gif" ren "..\ad_1.gif" "Korroloka Tunnel 2.gif"
if exist "..\ad_2.gif" ren "..\ad_2.gif" "Korroloka Tunnel 3.gif"
if exist "..\ad_3.gif" ren "..\ad_3.gif" "Korroloka Tunnel 4.gif"
if exist "..\ad_4.gif" ren "..\ad_4.gif" "Korroloka Tunnel 5.gif"
if exist "..\ae_0.gif" ren "..\ae_0.gif" "Kuftal Tunnel 1.gif"
if exist "..\ae_1.gif" ren "..\ae_1.gif" "Kuftal Tunnel 2.gif"
if exist "..\ae_2.gif" ren "..\ae_2.gif" "Kuftal Tunnel 3.gif"
if exist "..\ae_3.gif" ren "..\ae_3.gif" "Kuftal Tunnel 4.gif"
if exist "..\84_0.gif" ren "..\84_0.gif" "La Theine Plateau [A].gif"
if exist "..\66_0.gif" ren "..\66_0.gif" "La Theine Plateau.gif"
if exist "..\d5_0.gif" ren "..\d5_0.gif" "Labyrinth of Onzozo.gif"
if exist "..\b4_0.gif" ren "..\b4_0.gif" "La'Loff Amphitheater.gif"
if exist "..\3f_0.gif" ren "..\3f_0.gif" "Lebros Cavern 1.gif"
if exist "..\3f_9.gif" ren "..\3f_9.gif" "Lebros Cavern 10.gif"
if exist "..\3f_1.gif" ren "..\3f_1.gif" "Lebros Cavern 2.gif"
if exist "..\3f_2.gif" ren "..\3f_2.gif" "Lebros Cavern 3.gif"
if exist "..\3f_3.gif" ren "..\3f_3.gif" "Lebros Cavern 4.gif"
if exist "..\3f_4.gif" ren "..\3f_4.gif" "Lebros Cavern 5.gif"
if exist "..\3f_5.gif" ren "..\3f_5.gif" "Lebros Cavern 6.gif"
if exist "..\3f_6.gif" ren "..\3f_6.gif" "Lebros Cavern 7.gif"
if exist "..\3f_7.gif" ren "..\3f_7.gif" "Lebros Cavern 8.gif"
if exist "..\3f_8.gif" ren "..\3f_8.gif" "Lebros Cavern 9.gif"
if exist "..\45_0.gif" ren "..\45_0.gif" "Leujaoam Sanctum 1.gif"
if exist "..\45_9.gif" ren "..\45_9.gif" "Leujaoam Sanctum 10.gif"
if exist "..\45_1.gif" ren "..\45_1.gif" "Leujaoam Sanctum 2.gif"
if exist "..\45_2.gif" ren "..\45_2.gif" "Leujaoam Sanctum 3.gif"
if exist "..\45_3.gif" ren "..\45_3.gif" "Leujaoam Sanctum 4.gif"
if exist "..\45_4.gif" ren "..\45_4.gif" "Leujaoam Sanctum 5.gif"
if exist "..\45_5.gif" ren "..\45_5.gif" "Leujaoam Sanctum 6.gif"
if exist "..\45_6.gif" ren "..\45_6.gif" "Leujaoam Sanctum 7.gif"
if exist "..\45_7.gif" ren "..\45_7.gif" "Leujaoam Sanctum 8.gif"
if exist "..\45_8.gif" ren "..\45_8.gif" "Leujaoam Sanctum 9.gif"
if exist "..\f5_0.gif" ren "..\f5_0.gif" "Lower Jeuno.gif"
if exist "..\18_0.gif" ren "..\18_0.gif" "Lufaise Meadows.gif"
if exist "..\41_0.gif" ren "..\41_0.gif" "Mamook 1.gif"
if exist "..\41_1.gif" ren "..\41_1.gif" "Mamook 2.gif"
if exist "..\41_2.gif" ren "..\41_2.gif" "Mamook 3.gif"
if exist "..\42_0.gif" ren "..\42_0.gif" "Mamool Ja Training Grounds 1.gif"
if exist "..\42_9.gif" ren "..\42_9.gif" "Mamool Ja Training Grounds 10.gif"
if exist "..\42_1.gif" ren "..\42_1.gif" "Mamool Ja Training Grounds 2.gif"
if exist "..\42_2.gif" ren "..\42_2.gif" "Mamool Ja Training Grounds 3.gif"
if exist "..\42_3.gif" ren "..\42_3.gif" "Mamool Ja Training Grounds 4.gif"
if exist "..\42_4.gif" ren "..\42_4.gif" "Mamool Ja Training Grounds 5.gif"
if exist "..\42_5.gif" ren "..\42_5.gif" "Mamool Ja Training Grounds 6.gif"
if exist "..\42_6.gif" ren "..\42_6.gif" "Mamool Ja Training Grounds 7.gif"
if exist "..\42_7.gif" ren "..\42_7.gif" "Mamool Ja Training Grounds 8.gif"
if exist "..\42_8.gif" ren "..\42_8.gif" "Mamool Ja Training Grounds 9.gif"
if exist "..\03_0.gif" ren "..\03_0.gif" "Manaclipper.gif"
if exist "..\c6_0.gif" ren "..\c6_0.gif" "Maze of Shakhrami 1.gif"
if exist "..\c6_1.gif" ren "..\c6_1.gif" "Maze of Shakhrami 2.gif"
if exist "..\c6_2.gif" ren "..\c6_2.gif" "Maze of Shakhrami Unknown.gif"
if exist "..\61_0.gif" ren "..\61_0.gif" "Meriphataud Mountains [S].gif"
if exist "..\77_0.gif" ren "..\77_0.gif" "Meriphataud Mountains.gif"
if exist "..\ed_0.gif" ren "..\ed_0.gif" "Metalworks.gif"
if exist "..\f9_0.gif" ren "..\f9_0.gif" "Mhaura.gif"
if exist "..\0d_0.gif" ren "..\0d_0.gif" "Mine Shaft #2716.gif"
if exist "..\19_0.gif" ren "..\19_0.gif" "Misareaux Coast.gif"
if exist "..\1f_0.gif" ren "..\1f_0.gif" "Monarch Linn.gif"
if exist "..\96_0.gif" ren "..\96_0.gif" "Monastic Cavern.gif"
if exist "..\83_0.gif" ren "..\83_0.gif" "Mordion Gaol.gif"
if exist "..\3d_0.gif" ren "..\3d_0.gif" "Mount Zhayolm.gif"
if exist "..\35_0.gif" ren "..\35_0.gif" "Nashmau.gif"
if exist "..\0c_0.gif" ren "..\0c_0.gif" "Newton Movalpolos.gif"
if exist "..\fc_0.gif" ren "..\fc_0.gif" "Norg.gif"
if exist "..\58_0.gif" ren "..\58_0.gif" "North Gustaberg [S].gif"
if exist "..\6a_0.gif" ren "..\6a_0.gif" "North Gustaberg.gif"
if exist "..\e7_0.gif" ren "..\e7_0.gif" "Northern San d'Oria.gif"
if exist "..\4d_0.gif" ren "..\4d_0.gif" "Nyzul Isle 1.gif"
if exist "..\4d_1.gif" ren "..\4d_1.gif" "Nyzul Isle 2.gif"
if exist "..\4d_2.gif" ren "..\4d_2.gif" "Nyzul Isle 3.gif"
if exist "..\4d_3.gif" ren "..\4d_3.gif" "Nyzul Isle 4.gif"
if exist "..\4d_4.gif" ren "..\4d_4.gif" "Nyzul Isle 5.gif"
if exist "..\4d_5.gif" ren "..\4d_5.gif" "Nyzul Isle 6.gif"
if exist "..\4d_6.gif" ren "..\4d_6.gif" "Nyzul Isle 7.gif"
if exist "..\4d_7.gif" ren "..\4d_7.gif" "Nyzul Isle 8.gif"
if exist "..\0b_0.gif" ren "..\0b_0.gif" "Oldton Movalpolos.gif"
if exist "..\c1_0.gif" ren "..\c1_0.gif" "Ordelle's Caves 1 a.gif"
if exist "..\c1_3.gif" ren "..\c1_3.gif" "Ordelle's Caves 1 b.gif"
if exist "..\c1_1.gif" ren "..\c1_1.gif" "Ordelle's Caves 2.gif"
if exist "..\c1_2.gif" ren "..\c1_2.gif" "Ordelle's Caves 3.gif"
if exist "..\8f_0.gif" ren "..\8f_0.gif" "Palborough Mines 1.gif"
if exist "..\8f_1.gif" ren "..\8f_1.gif" "Palborough Mines 2.gif"
if exist "..\8f_2.gif" ren "..\8f_2.gif" "Palborough Mines 3.gif"
if exist "..\5a_0.gif" ren "..\5a_0.gif" "Pashhow Marshlands [S].gif"
if exist "..\6d_0.gif" ren "..\6d_0.gif" "Pashhow Marshlands.gif"
if exist "..\38_0.gif" ren "..\38_0.gif" "Periqia 1.gif"
if exist "..\38_9.gif" ren "..\38_9.gif" "Periqia 10.gif"
if exist "..\38_1.gif" ren "..\38_1.gif" "Periqia 2.gif"
if exist "..\38_2.gif" ren "..\38_2.gif" "Periqia 3.gif"
if exist "..\38_3.gif" ren "..\38_3.gif" "Periqia 4.gif"
if exist "..\38_4.gif" ren "..\38_4.gif" "Periqia 5.gif"
if exist "..\38_5.gif" ren "..\38_5.gif" "Periqia 6.gif"
if exist "..\38_6.gif" ren "..\38_6.gif" "Periqia 7.gif"
if exist "..\38_7.gif" ren "..\38_7.gif" "Periqia 8.gif"
if exist "..\38_8.gif" ren "..\38_8.gif" "Periqia 9.gif"
if exist "..\01_0.gif" ren "..\01_0.gif" "Phanauet Channel.gif"
if exist "..\1b_0.gif" ren "..\1b_0.gif" "Phomiuna Aqueducts 1.gif"
if exist "..\1b_1.gif" ren "..\1b_1.gif" "Phomiuna Aqueducts 2.gif"
if exist "..\1b_2.gif" ren "..\1b_2.gif" "Phomiuna Aqueducts 3.gif"
if exist "..\ec_0.gif" ren "..\ec_0.gif" "Port Bastok.gif"
if exist "..\f6_0.gif" ren "..\f6_0.gif" "Port Jeuno.gif"
if exist "..\e8_0.gif" ren "..\e8_0.gif" "Port San d'Oria.gif"
if exist "..\f0_0.gif" ren "..\f0_0.gif" "Port Windurst.gif"
if exist "..\12_0.gif" ren "..\12_0.gif" "Promyvion - Dem.gif"
if exist "..\10_0.gif" ren "..\10_0.gif" "Promyvion - Holla.gif"
if exist "..\14_0.gif" ren "..\14_0.gif" "Promyvion - Mea.gif"
if exist "..\16_0.gif" ren "..\16_0.gif" "Promyvion - Vahzl.gif"
if exist "..\09_0.gif" ren "..\09_0.gif" "Pso'Xja 1.gif"
if exist "..\09_9.gif" ren "..\09_9.gif" "Pso'Xja 10.gif"
if exist "..\09_10.gif" ren "..\09_10.gif" "Pso'Xja 11.gif"
if exist "..\09_11.gif" ren "..\09_11.gif" "Pso'Xja 12.gif"
if exist "..\09_12.gif" ren "..\09_12.gif" "Pso'Xja 13.gif"
if exist "..\09_13.gif" ren "..\09_13.gif" "Pso'Xja 14.gif"
if exist "..\09_14.gif" ren "..\09_14.gif" "Pso'Xja 15.gif"
if exist "..\09_15.gif" ren "..\09_15.gif" "Pso'Xja 16.gif"
if exist "..\09_16.gif" ren "..\09_16.gif" "Pso'Xja 17.gif"
if exist "..\09_17.gif" ren "..\09_17.gif" "Pso'Xja 18.gif"
if exist "..\09_18.gif" ren "..\09_18.gif" "Pso'Xja 19.gif"
if exist "..\09_1.gif" ren "..\09_1.gif" "Pso'Xja 2.gif"
if exist "..\09_19.gif" ren "..\09_19.gif" "Pso'Xja 20.gif"
if exist "..\09_20.gif" ren "..\09_20.gif" "Pso'Xja 21.gif"
if exist "..\09_2.gif" ren "..\09_2.gif" "Pso'Xja 3.gif"
if exist "..\09_3.gif" ren "..\09_3.gif" "Pso'Xja 4.gif"
if exist "..\09_4.gif" ren "..\09_4.gif" "Pso'Xja 5.gif"
if exist "..\09_5.gif" ren "..\09_5.gif" "Pso'Xja 6.gif"
if exist "..\09_6.gif" ren "..\09_6.gif" "Pso'Xja 7.gif"
if exist "..\09_7.gif" ren "..\09_7.gif" "Pso'Xja 8.gif"
if exist "..\09_8.gif" ren "..\09_8.gif" "Pso'Xja 9.gif"
if exist "..\04_1.gif" ren "..\04_1.gif" "Purgonorgo Isle.gif"
if exist "..\ce_0.gif" ren "..\ce_0.gif" "Qu'Bia Arena.gif"
if exist "..\7e_0.gif" ren "..\7e_0.gif" "Qufim Island.gif"
if exist "..\d0_0.gif" ren "..\d0_0.gif" "Quicksand Caves 1.gif"
if exist "..\d0_1.gif" ren "..\d0_1.gif" "Quicksand Caves 2.gif"
if exist "..\d0_2.gif" ren "..\d0_2.gif" "Quicksand Caves 3.gif"
if exist "..\d0_3.gif" ren "..\d0_3.gif" "Quicksand Caves 4.gif"
if exist "..\d0_4.gif" ren "..\d0_4.gif" "Quicksand Caves 5.gif"
if exist "..\d0_5.gif" ren "..\d0_5.gif" "Quicksand Caves 6.gif"
if exist "..\d0_6.gif" ren "..\d0_6.gif" "Quicksand Caves 7.gif"
if exist "..\d0_7.gif" ren "..\d0_7.gif" "Quicksand Caves 8.gif"
if exist "..\94_0.gif" ren "..\94_0.gif" "Qulun Dome.gif"
if exist "..\f7_0.gif" ren "..\f7_0.gif" "Rabao.gif"
if exist "..\a6_0.gif" ren "..\a6_0.gif" "Ranguemont Pass.gif"
if exist "..\1e_0.gif" ren "..\1e_0.gif" "Riverne - Site #A01 a.gif"
if exist "..\1e_1.gif" ren "..\1e_1.gif" "Riverne - Site #A01 b.gif"
if exist "..\1d_0.gif" ren "..\1d_0.gif" "Riverne - Site #B01 a.gif"
if exist "..\1d_1.gif" ren "..\1d_1.gif" "Riverne - Site #B01 b.gif"
if exist "..\5b_0.gif" ren "..\5b_0.gif" "Rolanberry Fields [S].gif"
if exist "..\6e_0.gif" ren "..\6e_0.gif" "Rolanberry Fields.gif"
if exist "..\7a_0.gif" ren "..\7a_0.gif" "Ro'Maeve.gif"
if exist "..\82_0.gif" ren "..\82_0.gif" "Ru'Aun Gardens.gif"
if exist "..\f3_0.gif" ren "..\f3_0.gif" "Ru'Lude Gardens.gif"
if exist "..\5d_0.gif" ren "..\5d_0.gif" "Ruthotz Silvermines 1.gif"
if exist "..\5d_9.gif" ren "..\5d_9.gif" "Ruthotz Silvermines 10.gif"
if exist "..\5d_10.gif" ren "..\5d_10.gif" "Ruthotz Silvermines 11.gif"
if exist "..\5d_11.gif" ren "..\5d_11.gif" "Ruthotz Silvermines 12.gif"
if exist "..\5d_12.gif" ren "..\5d_12.gif" "Ruthotz Silvermines 13.gif"
if exist "..\5d_13.gif" ren "..\5d_13.gif" "Ruthotz Silvermines 14.gif"
if exist "..\5d_14.gif" ren "..\5d_14.gif" "Ruthotz Silvermines 15.gif"
if exist "..\5d_15.gif" ren "..\5d_15.gif" "Ruthotz Silvermines 16.gif"
if exist "..\5d_16.gif" ren "..\5d_16.gif" "Ruthotz Silvermines 17.gif"
if exist "..\5d_17.gif" ren "..\5d_17.gif" "Ruthotz Silvermines 18.gif"
if exist "..\5d_1.gif" ren "..\5d_1.gif" "Ruthotz Silvermines 2.gif"
if exist "..\5d_2.gif" ren "..\5d_2.gif" "Ruthotz Silvermines 3.gif"
if exist "..\5d_3.gif" ren "..\5d_3.gif" "Ruthotz Silvermines 4.gif"
if exist "..\5d_4.gif" ren "..\5d_4.gif" "Ruthotz Silvermines 5.gif"
if exist "..\5d_5.gif" ren "..\5d_5.gif" "Ruthotz Silvermines 6.gif"
if exist "..\5d_6.gif" ren "..\5d_6.gif" "Ruthotz Silvermines 7.gif"
if exist "..\5d_7.gif" ren "..\5d_7.gif" "Ruthotz Silvermines 8.gif"
if exist "..\5d_8.gif" ren "..\5d_8.gif" "Ruthotz Silvermines 9.gif"
if exist "..\1c_0.gif" ren "..\1c_0.gif" "Sacrarium 1.gif"
if exist "..\1c_1.gif" ren "..\1c_1.gif" "Sacrarium 2.gif"
if exist "..\a3_0.gif" ren "..\a3_0.gif" "Sacrificial Chamber.gif"
if exist "..\d8_0.gif" ren "..\d8_0.gif" "San d'Oria Residential Area.gif"
if exist "..\62_0.gif" ren "..\62_0.gif" "Sauromugue Champaign [S].gif"
if exist "..\78_0.gif" ren "..\78_0.gif" "Sauromugue Champaign.gif"
if exist "..\b0_0.gif" ren "..\b0_0.gif" "Sea Serpent Grotto 1.gif"
if exist "..\b0_1.gif" ren "..\b0_1.gif" "Sea Serpent Grotto 2.gif"
if exist "..\b0_2.gif" ren "..\b0_2.gif" "Sea Serpent Grotto 3.gif"
if exist "..\b0_3.gif" ren "..\b0_3.gif" "Sea Serpent Grotto 4.gif"
if exist "..\b0_4.gif" ren "..\b0_4.gif" "Sea Serpent Grotto 5.gif"
if exist "..\20_0.gif" ren "..\20_0.gif" "Sealion's Den.gif"
if exist "..\f8_0.gif" ren "..\f8_0.gif" "Selbina.gif"
if exist "..\4c_0.gif" ren "..\4c_0.gif" "Silver Sea Remnants 1.gif"
if exist "..\4c_1.gif" ren "..\4c_1.gif" "Silver Sea Remnants 2.gif"
if exist "..\4c_2.gif" ren "..\4c_2.gif" "Silver Sea Remnants 3.gif"
if exist "..\4c_3.gif" ren "..\4c_3.gif" "Silver Sea Remnants 4.gif"
if exist "..\4c_4.gif" ren "..\4c_4.gif" "Silver Sea Remnants 5.gif"
if exist "..\6b_0.gif" ren "..\6b_0.gif" "South Gustaberg.gif"
if exist "..\50_0.gif" ren "..\50_0.gif" "Southern San d'Oria [S].gif"
if exist "..\e6_0.gif" ren "..\e6_0.gif" "Southern San d'Oria.gif"
if exist "..\13_0.gif" ren "..\13_0.gif" "Spire of Dem.gif"
if exist "..\11_0.gif" ren "..\11_0.gif" "Spire of Holla.gif"
if exist "..\15_0.gif" ren "..\15_0.gif" "Spire of Mea.gif"
if exist "..\17_0.gif" ren "..\17_0.gif" "Spire of Vahzl.gif"
if exist "..\b3_0.gif" ren "..\b3_0.gif" "Stellar Fulcrum.gif"
if exist "..\2d_0.gif" ren "..\2d_0.gif" "Tahrongi Canyon [A].gif"
if exist "..\75_0.gif" ren "..\75_0.gif" "Tahrongi Canyon.gif"
if exist "..\39_0.gif" ren "..\39_0.gif" "Talacca Cove.gif"
if exist "..\1a_0.gif" ren "..\1a_0.gif" "Tavnazian Safehold 1.gif"
if exist "..\1a_1.gif" ren "..\1a_1.gif" "Tavnazian Safehold 2.gif"
if exist "..\1a_2.gif" ren "..\1a_2.gif" "Tavnazian Safehold 3.gif"
if exist "..\25_21.gif" ren "..\25_21.gif" "Temenos-C1.gif"
if exist "..\25_22.gif" ren "..\25_22.gif" "Temenos-C2.gif"
if exist "..\25_23.gif" ren "..\25_23.gif" "Temenos-C3.gif"
if exist "..\25_24.gif" ren "..\25_24.gif" "Temenos-C4.gif"
if exist "..\25_25.gif" ren "..\25_25.gif" "Temenos-CB1.gif"
if exist "..\25_7.gif" ren "..\25_7.gif" "Temenos-E1.gif"
if exist "..\25_8.gif" ren "..\25_8.gif" "Temenos-E2.gif"
if exist "..\25_9.gif" ren "..\25_9.gif" "Temenos-E3.gif"
if exist "..\25_10.gif" ren "..\25_10.gif" "Temenos-E4.gif"
if exist "..\25_11.gif" ren "..\25_11.gif" "Temenos-E5.gif"
if exist "..\25_12.gif" ren "..\25_12.gif" "Temenos-E6.gif"
if exist "..\25_13.gif" ren "..\25_13.gif" "Temenos-E7.gif"
if exist "..\25_26.gif" ren "..\25_26.gif" "Temenos-Entrance.gif"
if exist "..\25_0.gif" ren "..\25_0.gif" "Temenos-N1.gif"
if exist "..\25_1.gif" ren "..\25_1.gif" "Temenos-N2.gif"
if exist "..\25_2.gif" ren "..\25_2.gif" "Temenos-N3.gif"
if exist "..\25_3.gif" ren "..\25_3.gif" "Temenos-N4.gif"
if exist "..\25_4.gif" ren "..\25_4.gif" "Temenos-N5.gif"
if exist "..\25_5.gif" ren "..\25_5.gif" "Temenos-N6.gif"
if exist "..\25_6.gif" ren "..\25_6.gif" "Temenos-N7.gif"
if exist "..\25_14.gif" ren "..\25_14.gif" "Temenos-W1.gif"
if exist "..\25_15.gif" ren "..\25_15.gif" "Temenos-W2.gif"
if exist "..\25_16.gif" ren "..\25_16.gif" "Temenos-W3.gif"
if exist "..\25_17.gif" ren "..\25_17.gif" "Temenos-W4.gif"
if exist "..\25_18.gif" ren "..\25_18.gif" "Temenos-W5.gif"
if exist "..\25_19.gif" ren "..\25_19.gif" "Temenos-W6.gif"
if exist "..\25_20.gif" ren "..\25_20.gif" "Temenos-W7.gif"
if exist "..\9f_0.gif" ren "..\9f_0.gif" "Temple of Uggalepih 1.gif"
if exist "..\9f_1.gif" ren "..\9f_1.gif" "Temple of Uggalepih 2.gif"
if exist "..\9f_2.gif" ren "..\9f_2.gif" "Temple of Uggalepih 3.gif"
if exist "..\9f_3.gif" ren "..\9f_3.gif" "Temple of Uggalepih 4.gif"
if exist "..\99_0.gif" ren "..\99_0.gif" "The Boyahda Tree 1.gif"
if exist "..\99_1.gif" ren "..\99_1.gif" "The Boyahda Tree 2.gif"
if exist "..\99_2.gif" ren "..\99_2.gif" "The Boyahda Tree 3.gif"
if exist "..\99_3.gif" ren "..\99_3.gif" "The Boyahda Tree 4.gif"
if exist "..\b5_0.gif" ren "..\b5_0.gif" "The Celestial Nexus.gif"
if exist "..\47_0.gif" ren "..\47_0.gif" "The Colosseum 1.gif"
if exist "..\47_1.gif" ren "..\47_1.gif" "The Colosseum 2.gif"
if exist "..\c3_0.gif" ren "..\c3_0.gif" "The Eldieme Necropolis 1.gif"
if exist "..\c3_1.gif" ren "..\c3_1.gif" "The Eldieme Necropolis 2.gif"
if exist "..\c3_2.gif" ren "..\c3_2.gif" "The Eldieme Necropolis 3.gif"
if exist "..\23_0.gif" ren "..\23_0.gif" "The Garden of Ru'Hmet 1.gif"
if exist "..\23_1.gif" ren "..\23_1.gif" "The Garden of Ru'Hmet 2.gif"
if exist "..\23_2.gif" ren "..\23_2.gif" "The Garden of Ru'Hmet 3.gif"
if exist "..\23_3.gif" ren "..\23_3.gif" "The Garden of Ru'Hmet 4.gif"
if exist "..\b7_0.gif" ren "..\b7_0.gif" "The Last Stand.gif"
if exist "..\79_0.gif" ren "..\79_0.gif" "The Sanctuary of Zi'Tah.gif"
if exist "..\b2_0.gif" ren "..\b2_0.gif" "The Shrine of Ru'Avitau 1.gif"
if exist "..\b2_1.gif" ren "..\b2_1.gif" "The Shrine of Ru'Avitau 2.gif"
if exist "..\b2_2.gif" ren "..\b2_2.gif" "The Shrine of Ru'Avitau 3.gif"
if exist "..\b2_3.gif" ren "..\b2_3.gif" "The Shrine of Ru'Avitau 4.gif"
if exist "..\b2_4.gif" ren "..\b2_4.gif" "The Shrine of Ru'Avitau 5.gif"
if exist "..\b2_5.gif" ren "..\b2_5.gif" "The Shrine of Ru'Avitau 6.gif"
if exist "..\0a_0.gif" ren "..\0a_0.gif" "The Shrouded Maw.gif"
if exist "..\a5_0.gif" ren "..\a5_0.gif" "Throne Room.gif"
if exist "..\a9_0.gif" ren "..\a9_0.gif" "Toraimarai Canal 1.gif"
if exist "..\a9_1.gif" ren "..\a9_1.gif" "Toraimarai Canal 2.gif"
if exist "..\05_0.gif" ren "..\05_0.gif" "Uleguerand Range.gif"
if exist "..\f4_0.gif" ren "..\f4_0.gif" "Upper Jeuno.gif"
if exist "..\67_0.gif" ren "..\67_0.gif" "Valkurm Dunes.gif"
if exist "..\80_0.gif" ren "..\80_0.gif" "Valley of Sorrows.gif"
if exist "..\b1_0.gif" ren "..\b1_0.gif" "Ve'Lugannon Palace 1.gif"
if exist "..\b1_1.gif" ren "..\b1_1.gif" "Ve'Lugannon Palace 2.gif"
if exist "..\b1_2.gif" ren "..\b1_2.gif" "Ve'Lugannon Palace 3.gif"
if exist "..\b1_3.gif" ren "..\b1_3.gif" "Ve'Lugannon Palace 4.gif"
if exist "..\b1_4.gif" ren "..\b1_4.gif" "Ve'Lugannon Palace 5.gif"
if exist "..\b1_5.gif" ren "..\b1_5.gif" "Ve'Lugannon Palace 6.gif"
if exist "..\b1_6.gif" ren "..\b1_6.gif" "Ve'Lugannon Palace 7.gif"
if exist "..\b1_7.gif" ren "..\b1_7.gif" "Ve'Lugannon Palace 8.gif"
if exist "..\b1_8.gif" ren "..\b1_8.gif" "Ve'Lugannon Palace 9.gif"
if exist "..\53_0.gif" ren "..\53_0.gif" "Vunkerl Inlet.gif"
if exist "..\33_0.gif" ren "..\33_0.gif" "Wajaom Woodlands.gif"
if exist "..\b6_0.gif" ren "..\b6_0.gif" "Walk of Echoes.gif"
if exist "..\90_0.gif" ren "..\90_0.gif" "Waughroon Shrine.gif"
if exist "..\64_0.gif" ren "..\64_0.gif" "West Ronfaure.gif"
if exist "..\73_0.gif" ren "..\73_0.gif" "West Sarutabaruta.gif"
if exist "..\5f_0.gif" ren "..\5f_0.gif" "West Sarutaburuta [S].gif"
if exist "..\7d_0.gif" ren "..\7d_0.gif" "Western Altepa Desert.gif"
if exist "..\da_0.gif" ren "..\da_0.gif" "Windurst Residential Area.gif"
if exist "..\ef_0.gif" ren "..\ef_0.gif" "Windurst Walls.gif"
if exist "..\5e_0.gif" ren "..\5e_0.gif" "Windurst Waters 1 [S].gif"
if exist "..\ee_0.gif" ren "..\ee_0.gif" "Windurst Waters 1.gif"
if exist "..\5e_1.gif" ren "..\5e_1.gif" "Windurst Waters 2 [S].gif"
if exist "..\ee_1.gif" ren "..\ee_1.gif" "Windurst Waters 2.gif"
if exist "..\f1_0.gif" ren "..\f1_0.gif" "Windurst Woods.gif"
if exist "..\89_0.gif" ren "..\89_0.gif" "Xarcabard [S].gif"
if exist "..\70_0.gif" ren "..\70_0.gif" "Xarcabard.gif"
if exist "..\7c_0.gif" ren "..\7c_0.gif" "Yhoator Jungle.gif"
if exist "..\8e_0.gif" ren "..\8e_0.gif" "Yughott Grotto 1.gif"
if exist "..\8e_1.gif" ren "..\8e_1.gif" "Yughott Grotto 2.gif"
if exist "..\7b_0.gif" ren "..\7b_0.gif" "Yuhtunga Jungle.gif"
if exist "..\ac_0.gif" ren "..\ac_0.gif" "Zeruhn Mines.gif "
if exist "..\49_0.gif" ren "..\49_0.gif" "Zhayolm Remnants 1.gif"
if exist "..\49_1.gif" ren "..\49_1.gif" "Zhayolm Remnants 2.gif"
if exist "..\49_2.gif" ren "..\49_2.gif" "Zhayolm Remnants 3.gif"
if exist "..\49_3.gif" ren "..\49_3.gif" "Zhayolm Remnants 4.gif"
if exist "..\49_4.gif" ren "..\49_4.gif" "Zhayolm Remnants 5.gif"
if exist "..\49_5.gif" ren "..\49_5.gif" "Zhayolm Remnants 6.gif"
if exist "..\49_6.gif" ren "..\49_6.gif" "Zhayolm Remnants 7.gif"