if exist "..\Aht Urhgan Whitegate.gif" ren "..\Aht Urhgan Whitegate.gif" "32_0.gif"
if exist "..\Airship - Jeuno-Bastok.gif" ren "..\Airship - Jeuno-Bastok.gif" "e0_0.gif"
if exist "..\Airship - Jeuno-Kazham.gif" ren "..\Airship - Jeuno-Kazham.gif" "e2_0.gif"
if exist "..\Airship - Jeuno-SandOria.gif" ren "..\Airship - Jeuno-SandOria.gif" "df_0.gif"
if exist "..\Airship - Jeuno-Windurst.gif" ren "..\Airship - Jeuno-Windurst.gif" "e1_0.gif"
if exist "..\Al Zhabi Residential Area.gif" ren "..\Al Zhabi Residential Area.gif" "d6_0.gif"
if exist "..\Al Zhabi.gif" ren "..\Al Zhabi.gif" "30_0.gif"
if exist "..\Al'Taieu.gif" ren "..\Al'Taieu.gif" "21_0.gif"
if exist "..\Altar Room.gif" ren "..\Altar Room.gif" "98_0.gif"
if exist "..\Alzadaal Undersea Ruins 1.gif" ren "..\Alzadaal Undersea Ruins 1.gif" "48_0.gif"
if exist "..\Alzadaal Undersea Ruins 10.gif" ren "..\Alzadaal Undersea Ruins 10.gif" "48_9.gif"
if exist "..\Alzadaal Undersea Ruins 11.gif" ren "..\Alzadaal Undersea Ruins 11.gif" "48_10.gif"
if exist "..\Alzadaal Undersea Ruins 12.gif" ren "..\Alzadaal Undersea Ruins 12.gif" "48_11.gif"
if exist "..\Alzadaal Undersea Ruins 2.gif" ren "..\Alzadaal Undersea Ruins 2.gif" "48_1.gif"
if exist "..\Alzadaal Undersea Ruins 3.gif" ren "..\Alzadaal Undersea Ruins 3.gif" "48_2.gif"
if exist "..\Alzadaal Undersea Ruins 4.gif" ren "..\Alzadaal Undersea Ruins 4.gif" "48_3.gif"
if exist "..\Alzadaal Undersea Ruins 5.gif" ren "..\Alzadaal Undersea Ruins 5.gif" "48_4.gif"
if exist "..\Alzadaal Undersea Ruins 6.gif" ren "..\Alzadaal Undersea Ruins 6.gif" "48_5.gif"
if exist "..\Alzadaal Undersea Ruins 7.gif" ren "..\Alzadaal Undersea Ruins 7.gif" "48_6.gif"
if exist "..\Alzadaal Undersea Ruins 8.gif" ren "..\Alzadaal Undersea Ruins 8.gif" "48_7.gif"
if exist "..\Alzadaal Undersea Ruins 9.gif" ren "..\Alzadaal Undersea Ruins 9.gif" "48_8.gif"
if exist "..\Apollyon-CN.gif" ren "..\Apollyon-CN.gif" "26_6.gif"
if exist "..\Apollyon-CS.gif" ren "..\Apollyon-CS.gif" "26_7.gif"
if exist "..\Apollyon-Entrance-SE.gif" ren "..\Apollyon-Entrance-SE.gif" "26_0.gif"
if exist "..\Apollyon-Entrance-SW.gif" ren "..\Apollyon-Entrance-SW.gif" "26_1.gif"
if exist "..\Apollyon-NE.gif" ren "..\Apollyon-NE.gif" "26_2.gif"
if exist "..\Apollyon-NW.gif" ren "..\Apollyon-NW.gif" "26_3.gif"
if exist "..\Apollyon-SE.gif" ren "..\Apollyon-SE.gif" "26_4.gif"
if exist "..\Apollyon-SW.gif" ren "..\Apollyon-SW.gif" "26_5.gif"
if exist "..\Arrapago Reef 1.gif" ren "..\Arrapago Reef 1.gif" "36_0.gif"
if exist "..\Arrapago Reef 10.gif" ren "..\Arrapago Reef 10.gif" "36_9.gif"
if exist "..\Arrapago Reef 11.gif" ren "..\Arrapago Reef 11.gif" "36_10.gif"
if exist "..\Arrapago Reef 2.gif" ren "..\Arrapago Reef 2.gif" "36_1.gif"
if exist "..\Arrapago Reef 3.gif" ren "..\Arrapago Reef 3.gif" "36_2.gif"
if exist "..\Arrapago Reef 4.gif" ren "..\Arrapago Reef 4.gif" "36_3.gif"
if exist "..\Arrapago Reef 5.gif" ren "..\Arrapago Reef 5.gif" "36_4.gif"
if exist "..\Arrapago Reef 6.gif" ren "..\Arrapago Reef 6.gif" "36_5.gif"
if exist "..\Arrapago Reef 7.gif" ren "..\Arrapago Reef 7.gif" "36_6.gif"
if exist "..\Arrapago Reef 8.gif" ren "..\Arrapago Reef 8.gif" "36_7.gif"
if exist "..\Arrapago Reef 9.gif" ren "..\Arrapago Reef 9.gif" "36_8.gif"
if exist "..\Arrapago Remnants 1.gif" ren "..\Arrapago Remnants 1.gif" "4a_0.gif"
if exist "..\Arrapago Remnants 2.gif" ren "..\Arrapago Remnants 2.gif" "4a_1.gif"
if exist "..\Arrapago Remnants 3.gif" ren "..\Arrapago Remnants 3.gif" "4a_2.gif"
if exist "..\Arrapago Remnants 4.gif" ren "..\Arrapago Remnants 4.gif" "4a_3.gif"
if exist "..\Arrapago Remnants 5.gif" ren "..\Arrapago Remnants 5.gif" "4a_4.gif"
if exist "..\Arrapago Remnants 6.gif" ren "..\Arrapago Remnants 6.gif" "4a_5.gif"
if exist "..\Arrapago Remnants 7.gif" ren "..\Arrapago Remnants 7.gif" "4a_6.gif"
if exist "..\Attohwa Chasm.gif" ren "..\Attohwa Chasm.gif" "07_0.gif"
if exist "..\Aydeewa Subterrane 1.gif" ren "..\Aydeewa Subterrane 1.gif" "44_0.gif"
if exist "..\Aydeewa Subterrane 2.gif" ren "..\Aydeewa Subterrane 2.gif" "44_1.gif"
if exist "..\Aydeewa Subterrane 3.gif" ren "..\Aydeewa Subterrane 3.gif" "44_2.gif"
if exist "..\Aydeewa Subterrane 4.gif" ren "..\Aydeewa Subterrane 4.gif" "44_3.gif"
if exist "..\Aydeewa Subterrane 5.gif" ren "..\Aydeewa Subterrane 5.gif" "44_4.gif"
if exist "..\Aydeewa Subterrane 6.gif" ren "..\Aydeewa Subterrane 6.gif" "44_5.gif"
if exist "..\Aydeewa Subterrane 7.gif" ren "..\Aydeewa Subterrane 7.gif" "44_6.gif"
if exist "..\Balga's Dais.gif" ren "..\Balga's Dais.gif" "92_0.gif"
if exist "..\Bastok Markets [S].gif" ren "..\Bastok Markets [S].gif" "57_0.gif"
if exist "..\Bastok Markets.gif" ren "..\Bastok Markets.gif" "eb_0.gif"
if exist "..\Bastok Mines.gif" ren "..\Bastok Mines.gif" "ea_0.gif"
if exist "..\Bastok Residential Area.gif" ren "..\Bastok Residential Area.gif" "d9_0.gif"
if exist "..\Batallia Downs [S].gif" ren "..\Batallia Downs [S].gif" "54_0.gif"
if exist "..\Batallia Downs.gif" ren "..\Batallia Downs.gif" "69_0.gif"
if exist "..\Beadeaux 1 [S].gif" ren "..\Beadeaux 1 [S].gif" "5c_0.gif"
if exist "..\Beadeaux 1.gif" ren "..\Beadeaux 1.gif" "93_0.gif"
if exist "..\Beadeaux 2 [S].gif" ren "..\Beadeaux 2 [S].gif" "5c_1.gif"
if exist "..\Beadeaux 2.gif" ren "..\Beadeaux 2.gif" "93_1.gif"
if exist "..\Beaucedine Glacier [S].gif" ren "..\Beaucedine Glacier [S].gif" "88_0.gif"
if exist "..\Beaucedine Glacier.gif" ren "..\Beaucedine Glacier.gif" "6f_0.gif"
if exist "..\Behemoth's Dominion.gif" ren "..\Behemoth's Dominion.gif" "7f_0.gif"
if exist "..\Bhaflau Remnants 1.gif" ren "..\Bhaflau Remnants 1.gif" "4b_0.gif"
if exist "..\Bhaflau Remnants 2.gif" ren "..\Bhaflau Remnants 2.gif" "4b_1.gif"
if exist "..\Bhaflau Remnants 3.gif" ren "..\Bhaflau Remnants 3.gif" "4b_2.gif"
if exist "..\Bhaflau Remnants 4.gif" ren "..\Bhaflau Remnants 4.gif" "4b_3.gif"
if exist "..\Bhaflau Remnants 5.gif" ren "..\Bhaflau Remnants 5.gif" "4b_4.gif"
if exist "..\Bhaflau Thickets 1.gif" ren "..\Bhaflau Thickets 1.gif" "34_0.gif"
if exist "..\Bhaflau Thickets 2.gif" ren "..\Bhaflau Thickets 2.gif" "34_1.gif"
if exist "..\Bibiki Bay.gif" ren "..\Bibiki Bay.gif" "04_0.gif"
if exist "..\Boneyard Gully.gif" ren "..\Boneyard Gully.gif" "08_0.gif"
if exist "..\Bostaunieux Oubliette 1.gif" ren "..\Bostaunieux Oubliette 1.gif" "a7_0.gif"
if exist "..\Bostaunieux Oubliette 2.gif" ren "..\Bostaunieux Oubliette 2.gif" "a7_1.gif"
if exist "..\Bostaunieux Oubliette 3.gif" ren "..\Bostaunieux Oubliette 3.gif" "a7_2.gif"
if exist "..\Buburimu Peninsula.gif" ren "..\Buburimu Peninsula.gif" "76_0.gif"
if exist "..\Caedarva Mire 1.gif" ren "..\Caedarva Mire 1.gif" "4f_0.gif"
if exist "..\Caedarva Mire 2.gif" ren "..\Caedarva Mire 2.gif" "4f_1.gif"
if exist "..\Caedarva Mire 3.gif" ren "..\Caedarva Mire 3.gif" "4f_2.gif"
if exist "..\Caedarva Mire 4.gif" ren "..\Caedarva Mire 4.gif" "4f_3.gif"
if exist "..\Cape Teriggan.gif" ren "..\Cape Teriggan.gif" "71_0.gif"
if exist "..\Carpenters' Landing 1.gif" ren "..\Carpenters' Landing 1.gif" "02_0.gif"
if exist "..\Carpenters' Landing 2.gif" ren "..\Carpenters' Landing 2.gif" "02_1.gif"
if exist "..\Castle Oztroja 1 [S].gif" ren "..\Castle Oztroja 1 [S].gif" "63_0.gif"
if exist "..\Castle Oztroja 1.gif" ren "..\Castle Oztroja 1.gif" "97_0.gif"
if exist "..\Castle Oztroja 2 [S].gif" ren "..\Castle Oztroja 2 [S].gif" "63_1.gif"
if exist "..\Castle Oztroja 2.gif" ren "..\Castle Oztroja 2.gif" "97_1.gif"
if exist "..\Castle Oztroja 3 [S].gif" ren "..\Castle Oztroja 3 [S].gif" "63_2.gif"
if exist "..\Castle Oztroja 3.gif" ren "..\Castle Oztroja 3.gif" "97_2.gif"
if exist "..\Castle Oztroja 4 [S].gif" ren "..\Castle Oztroja 4 [S].gif" "63_3.gif"
if exist "..\Castle Oztroja 4.gif" ren "..\Castle Oztroja 4.gif" "97_3.gif"
if exist "..\Castle Oztroja 5 [S].gif" ren "..\Castle Oztroja 5 [S].gif" "63_4.gif"
if exist "..\Castle Oztroja 5.gif" ren "..\Castle Oztroja 5.gif" "97_4.gif"
if exist "..\Castle Oztroja 6 [S].gif" ren "..\Castle Oztroja 6 [S].gif" "63_5.gif"
if exist "..\Castle Oztroja 6.gif" ren "..\Castle Oztroja 6.gif" "97_5.gif"
if exist "..\Castle Oztroja 7.gif" ren "..\Castle Oztroja 7.gif" "97_6.gif"
if exist "..\Castle Zvahl Baileys 1 [S].gif" ren "..\Castle Zvahl Baileys 1 [S].gif" "8a_0.gif"
if exist "..\Castle Zvahl Baileys 1.gif" ren "..\Castle Zvahl Baileys 1.gif" "a1_0.gif"
if exist "..\Castle Zvahl Baileys 2 [S].gif" ren "..\Castle Zvahl Baileys 2 [S].gif" "8a_1.gif"
if exist "..\Castle Zvahl Baileys 2.gif" ren "..\Castle Zvahl Baileys 2.gif" "a1_1.gif"
if exist "..\Castle Zvahl Baileys 3 [S].gif" ren "..\Castle Zvahl Baileys 3 [S].gif" "8a_2.gif"
if exist "..\Castle Zvahl Baileys 3.gif" ren "..\Castle Zvahl Baileys 3.gif" "a1_2.gif"
if exist "..\Castle Zvahl Baileys 4 [S].gif" ren "..\Castle Zvahl Baileys 4 [S].gif" "8a_3.gif"
if exist "..\Castle Zvahl Baileys 4.gif" ren "..\Castle Zvahl Baileys 4.gif" "a1_3.gif"
if exist "..\Castle Zvahl Keep 1 [S].gif" ren "..\Castle Zvahl Keep 1 [S].gif" "9b_0.gif"
if exist "..\Castle Zvahl Keep 1.gif" ren "..\Castle Zvahl Keep 1.gif" "a2_0.gif"
if exist "..\Castle Zvahl Keep 2 [S].gif" ren "..\Castle Zvahl Keep 2 [S].gif" "9b_1.gif"
if exist "..\Castle Zvahl Keep 2.gif" ren "..\Castle Zvahl Keep 2.gif" "a2_1.gif"
if exist "..\Castle Zvahl Keep 3 [S].gif" ren "..\Castle Zvahl Keep 3 [S].gif" "9b_2.gif"
if exist "..\Castle Zvahl Keep 3.gif" ren "..\Castle Zvahl Keep 3.gif" "a2_2.gif"
if exist "..\Castle Zvahl Keep 4 [S].gif" ren "..\Castle Zvahl Keep 4 [S].gif" "9b_3.gif"
if exist "..\Castle Zvahl Keep 4.gif" ren "..\Castle Zvahl Keep 4.gif" "a2_3.gif"
if exist "..\Chamber of Oracles.gif" ren "..\Chamber of Oracles.gif" "a8_0.gif"
if exist "..\Chateau d'Oraguille.gif" ren "..\Chateau d'Oraguille.gif" "e9_0.gif"
if exist "..\Chocobo Circuit 1.gif" ren "..\Chocobo Circuit 1.gif" "46_0.gif"
if exist "..\Chocobo Circuit 2.gif" ren "..\Chocobo Circuit 2.gif" "46_1.gif"
if exist "..\Chocobo Circuit 3.gif" ren "..\Chocobo Circuit 3.gif" "46_2.gif"
if exist "..\Chocobo Circuit 4.gif" ren "..\Chocobo Circuit 4.gif" "46_3.gif"
if exist "..\Chocobo Circuit 5.gif" ren "..\Chocobo Circuit 5.gif" "46_4.gif"
if exist "..\Chocobo Circuit 6.gif" ren "..\Chocobo Circuit 6.gif" "46_5.gif"
if exist "..\Chocobo Circuit 7.gif" ren "..\Chocobo Circuit 7.gif" "46_6.gif"
if exist "..\Cloister of Flames.gif" ren "..\Cloister of Flames.gif" "cf_0.gif"
if exist "..\Cloister of Frost.gif" ren "..\Cloister of Frost.gif" "cb_0.gif"
if exist "..\Cloister of Gales.gif" ren "..\Cloister of Gales.gif" "c9_0.gif"
if exist "..\Cloister of Storms.gif" ren "..\Cloister of Storms.gif" "ca_0.gif"
if exist "..\Cloister of Tides.gif" ren "..\Cloister of Tides.gif" "d3_0.gif"
if exist "..\Cloister of Tremors.gif" ren "..\Cloister of Tremors.gif" "d1_0.gif"
if exist "..\Crawlers Nest 1 [S].gif" ren "..\Crawlers Nest 1 [S].gif" "ab_0.gif"
if exist "..\Crawlers' Nest 1.gif" ren "..\Crawlers' Nest 1.gif" "c5_0.gif"
if exist "..\Crawlers Nest 2 [S].gif" ren "..\Crawlers Nest 2 [S].gif" "ab_1.gif"
if exist "..\Crawlers' Nest 2.gif" ren "..\Crawlers' Nest 2.gif" "c5_1.gif"
if exist "..\Crawlers' Nest 3.gif" ren "..\Crawlers' Nest 3.gif" "c5_2.gif"
if exist "..\Crawlers' Nest Unknown.gif" ren "..\Crawlers' Nest Unknown.gif" "c5_3.gif"
if exist "..\Dangruf Wadi a.gif" ren "..\Dangruf Wadi a.gif" "bf_0.gif"
if exist "..\Dangruf Wadi b.gif" ren "..\Dangruf Wadi b.gif" "bf_1.gif"
if exist "..\Davoi [S].gif" ren "..\Davoi [S].gif" "55_0.gif"
if exist "..\Davoi.gif" ren "..\Davoi.gif" "95_0.gif"
if exist "..\Delkfutt's Tower 0.gif" ren "..\Delkfutt's Tower 0.gif" "b8_3.gif"
if exist "..\Delkfutt's Tower 1.gif" ren "..\Delkfutt's Tower 1.gif" "b8_0.gif"
if exist "..\Delkfutt's Tower 10.gif" ren "..\Delkfutt's Tower 10.gif" "9e_0.gif"
if exist "..\Delkfutt's Tower 11.gif" ren "..\Delkfutt's Tower 11.gif" "9e_1.gif"
if exist "..\Delkfutt's Tower 12.gif" ren "..\Delkfutt's Tower 12.gif" "9e_2.gif"
if exist "..\Delkfutt's Tower 13.gif" ren "..\Delkfutt's Tower 13.gif" "9e_3.gif"
if exist "..\Delkfutt's Tower 14.gif" ren "..\Delkfutt's Tower 14.gif" "9e_4.gif"
if exist "..\Delkfutt's Tower 15.gif" ren "..\Delkfutt's Tower 15.gif" "9e_5.gif"
if exist "..\Delkfutt's Tower 2.gif" ren "..\Delkfutt's Tower 2.gif" "b8_1.gif"
if exist "..\Delkfutt's Tower 3.gif" ren "..\Delkfutt's Tower 3.gif" "b8_2.gif"
if exist "..\Delkfutt's Tower 4.gif" ren "..\Delkfutt's Tower 4.gif" "9d_0.gif"
if exist "..\Delkfutt's Tower 5.gif" ren "..\Delkfutt's Tower 5.gif" "9d_1.gif"
if exist "..\Delkfutt's Tower 6.gif" ren "..\Delkfutt's Tower 6.gif" "9d_2.gif"
if exist "..\Delkfutt's Tower 7.gif" ren "..\Delkfutt's Tower 7.gif" "9d_3.gif"
if exist "..\Delkfutt's Tower 8.gif" ren "..\Delkfutt's Tower 8.gif" "9d_4.gif"
if exist "..\Delkfutt's Tower 9.gif" ren "..\Delkfutt's Tower 9.gif" "9d_5.gif"
if exist "..\Den of Rancor 1.gif" ren "..\Den of Rancor 1.gif" "a0_0.gif"
if exist "..\Den of Rancor 2.gif" ren "..\Den of Rancor 2.gif" "a0_1.gif"
if exist "..\Den of Rancor 3.gif" ren "..\Den of Rancor 3.gif" "a0_2.gif"
if exist "..\Den of Rancor 4.gif" ren "..\Den of Rancor 4.gif" "a0_3.gif"
if exist "..\Den of Rancor 5.gif" ren "..\Den of Rancor 5.gif" "a0_4.gif"
if exist "..\Den of Rancor 6.gif" ren "..\Den of Rancor 6.gif" "a0_5.gif"
if exist "..\Den of Rancor 7.gif" ren "..\Den of Rancor 7.gif" "a0_6.gif"
if exist "..\Den of Rancor 8.gif" ren "..\Den of Rancor 8.gif" "a0_7.gif"
if exist "..\Den of Rancor 9.gif" ren "..\Den of Rancor 9.gif" "a0_8.gif"
if exist "..\Diorama Abdhaljs-Ghelsba.gif" ren "..\Diorama Abdhaljs-Ghelsba.gif" "2b_0.gif"
if exist "..\Diorama Abdhaljs-Purgonorgo Isle.gif" ren "..\Diorama Abdhaljs-Purgonorgo Isle.gif" "2c_0.gif"
if exist "..\Dragon's Aery.gif" ren "..\Dragon's Aery.gif" "9a_0.gif"
if exist "..\Dynamis - Bastok.gif" ren "..\Dynamis - Bastok.gif" "ba_0.gif"
if exist "..\Dynamis - Beaucedine.gif" ren "..\Dynamis - Beaucedine.gif" "86_0.gif"
if exist "..\Dynamis - Buburimu.gif" ren "..\Dynamis - Buburimu.gif" "28_0.gif"
if exist "..\Dynamis - Jeuno.gif" ren "..\Dynamis - Jeuno.gif" "bc_0.gif"
if exist "..\Dynamis - Qufim.gif" ren "..\Dynamis - Qufim.gif" "29_0.gif"
if exist "..\Dynamis - San d'Oria.gif" ren "..\Dynamis - San d'Oria.gif" "b9_0.gif"
if exist "..\Dynamis - Tavnazia 1.gif" ren "..\Dynamis - Tavnazia 1.gif" "2a_0.gif"
if exist "..\Dynamis - Tavnazia 2.gif" ren "..\Dynamis - Tavnazia 2.gif" "2a_1.gif"
if exist "..\Dynamis - Tavnazia 3.gif" ren "..\Dynamis - Tavnazia 3.gif" "2a_2.gif"
if exist "..\Dynamis - Valkurm.gif" ren "..\Dynamis - Valkurm.gif" "27_0.gif"
if exist "..\Dynamis - Windurst.gif" ren "..\Dynamis - Windurst.gif" "bb_0.gif"
if exist "..\Dynamis - Xarcabard.gif" ren "..\Dynamis - Xarcabard.gif" "87_0.gif"
if exist "..\East Ronfaure [S].gif" ren "..\East Ronfaure [S].gif" "51_0.gif"
if exist "..\East Ronfaure.gif" ren "..\East Ronfaure.gif" "65_0.gif"
if exist "..\East Sarutabaruta.gif" ren "..\East Sarutabaruta.gif" "74_0.gif"
if exist "..\Eastern Altepa Desert.gif" ren "..\Eastern Altepa Desert.gif" "72_0.gif"
if exist "..\Eldieme Necropolis 1 [S].gif" ren "..\Eldieme Necropolis 1 [S].gif" "af_0.gif"
if exist "..\Eldieme Necropolis 2 [S].gif" ren "..\Eldieme Necropolis 2 [S].gif" "af_1.gif"
if exist "..\Eldieme Necropolis 3 [S].gif" ren "..\Eldieme Necropolis 3 [S].gif" "af_2.gif"
if exist "..\Empyreal Paradox.gif" ren "..\Empyreal Paradox.gif" "24_0.gif"
if exist "..\Everbloom Hollow 1.gif" ren "..\Everbloom Hollow 1.gif" "56_0.gif"
if exist "..\Everbloom Hollow 10.gif" ren "..\Everbloom Hollow 10.gif" "56_9.gif"
if exist "..\Everbloom Hollow 11.gif" ren "..\Everbloom Hollow 11.gif" "56_10.gif"
if exist "..\Everbloom Hollow 12.gif" ren "..\Everbloom Hollow 12.gif" "56_11.gif"
if exist "..\Everbloom Hollow 13.gif" ren "..\Everbloom Hollow 13.gif" "56_12.gif"
if exist "..\Everbloom Hollow 14.gif" ren "..\Everbloom Hollow 14.gif" "56_13.gif"
if exist "..\Everbloom Hollow 15.gif" ren "..\Everbloom Hollow 15.gif" "56_14.gif"
if exist "..\Everbloom Hollow 16.gif" ren "..\Everbloom Hollow 16.gif" "56_15.gif"
if exist "..\Everbloom Hollow 17.gif" ren "..\Everbloom Hollow 17.gif" "56_16.gif"
if exist "..\Everbloom Hollow 18.gif" ren "..\Everbloom Hollow 18.gif" "56_17.gif"
if exist "..\Everbloom Hollow 2.gif" ren "..\Everbloom Hollow 2.gif" "56_1.gif"
if exist "..\Everbloom Hollow 3.gif" ren "..\Everbloom Hollow 3.gif" "56_2.gif"
if exist "..\Everbloom Hollow 4.gif" ren "..\Everbloom Hollow 4.gif" "56_3.gif"
if exist "..\Everbloom Hollow 5.gif" ren "..\Everbloom Hollow 5.gif" "56_4.gif"
if exist "..\Everbloom Hollow 6.gif" ren "..\Everbloom Hollow 6.gif" "56_5.gif"
if exist "..\Everbloom Hollow 7.gif" ren "..\Everbloom Hollow 7.gif" "56_6.gif"
if exist "..\Everbloom Hollow 8.gif" ren "..\Everbloom Hollow 8.gif" "56_7.gif"
if exist "..\Everbloom Hollow 9.gif" ren "..\Everbloom Hollow 9.gif" "56_8.gif"
if exist "..\Fei'Yin 1.gif" ren "..\Fei'Yin 1.gif" "cc_0.gif"
if exist "..\Fei'Yin 2.gif" ren "..\Fei'Yin 2.gif" "cc_1.gif"
if exist "..\Ferry - Mhaura-AlZahbi 1.gif" ren "..\Ferry - Mhaura-AlZahbi 1.gif" "2e_0.gif"
if exist "..\Ferry - Mhaura-AlZahbi 2.gif" ren "..\Ferry - Mhaura-AlZahbi 2.gif" "2f_0.gif"
if exist "..\Ferry - Nashmau-AlZahbi 1.gif" ren "..\Ferry - Nashmau-AlZahbi 1.gif" "3a_0.gif"
if exist "..\Ferry - Nashmau-AlZahbi 2.gif" ren "..\Ferry - Nashmau-AlZahbi 2.gif" "3b_0.gif"
if exist "..\Ferry - Selbina-Mhaura 1.gif" ren "..\Ferry - Selbina-Mhaura 1.gif" "dc_0.gif"
if exist "..\Ferry - Selbina-Mhaura 2.gif" ren "..\Ferry - Selbina-Mhaura 2.gif" "e3_0.gif"
if exist "..\Ferry - Selbina-Mhaura 3.gif" ren "..\Ferry - Selbina-Mhaura 3.gif" "dd_0.gif"
if exist "..\Ferry - Selbina-Mhaura 4.gif" ren "..\Ferry - Selbina-Mhaura 4.gif" "e4_0.gif"
if exist "..\Fort Ghelsba.gif" ren "..\Fort Ghelsba.gif" "8d_0.gif"
if exist "..\Fort Karugo-Narugo 1.gif" ren "..\Fort Karugo-Narugo 1.gif" "60_0.gif"
if exist "..\Fort Karugo-Narugo 2.gif" ren "..\Fort Karugo-Narugo 2.gif" "60_1.gif"
if exist "..\Full Moon Fountain.gif" ren "..\Full Moon Fountain.gif" "aa_0.gif"
if exist "..\Garlaige Citadel 1 [S].gif" ren "..\Garlaige Citadel 1 [S].gif" "a4_0.gif"
if exist "..\Garlaige Citadel 1.gif" ren "..\Garlaige Citadel 1.gif" "c8_0.gif"
if exist "..\Garlaige Citadel 2 [S].gif" ren "..\Garlaige Citadel 2 [S].gif" "a4_1.gif"
if exist "..\Garlaige Citadel 2.gif" ren "..\Garlaige Citadel 2.gif" "c8_1.gif"
if exist "..\Garlaige Citadel 3 [S].gif" ren "..\Garlaige Citadel 3 [S].gif" "a4_2.gif"
if exist "..\Garlaige Citadel 3.gif" ren "..\Garlaige Citadel 3.gif" "c8_2.gif"
if exist "..\Garlaige Citadel 4 [S].gif" ren "..\Garlaige Citadel 4 [S].gif" "a4_3.gif"
if exist "..\Garlaige Citadel 4.gif" ren "..\Garlaige Citadel 4.gif" "c8_3.gif"
if exist "..\Ghelsba Outpost 1.gif" ren "..\Ghelsba Outpost 1.gif" "8c_0.gif"
if exist "..\Ghelsba Outpost 2.gif" ren "..\Ghelsba Outpost 2.gif" "8c_1.gif"
if exist "..\Ghoyus Reverie 1.gif" ren "..\Ghoyus Reverie 1.gif" "81_0.gif"
if exist "..\Ghoyus Reverie 10.gif" ren "..\Ghoyus Reverie 10.gif" "81_9.gif"
if exist "..\Ghoyus Reverie 11.gif" ren "..\Ghoyus Reverie 11.gif" "81_10.gif"
if exist "..\Ghoyus Reverie 12.gif" ren "..\Ghoyus Reverie 12.gif" "81_11.gif"
if exist "..\Ghoyus Reverie 13.gif" ren "..\Ghoyus Reverie 13.gif" "81_12.gif"
if exist "..\Ghoyus Reverie 14.gif" ren "..\Ghoyus Reverie 14.gif" "81_13.gif"
if exist "..\Ghoyus Reverie 15.gif" ren "..\Ghoyus Reverie 15.gif" "81_14.gif"
if exist "..\Ghoyus Reverie 16.gif" ren "..\Ghoyus Reverie 16.gif" "81_15.gif"
if exist "..\Ghoyus Reverie 17.gif" ren "..\Ghoyus Reverie 17.gif" "81_16.gif"
if exist "..\Ghoyus Reverie 18.gif" ren "..\Ghoyus Reverie 18.gif" "81_17.gif"
if exist "..\Ghoyus Reverie 2.gif" ren "..\Ghoyus Reverie 2.gif" "81_1.gif"
if exist "..\Ghoyus Reverie 3.gif" ren "..\Ghoyus Reverie 3.gif" "81_2.gif"
if exist "..\Ghoyus Reverie 4.gif" ren "..\Ghoyus Reverie 4.gif" "81_3.gif"
if exist "..\Ghoyus Reverie 5.gif" ren "..\Ghoyus Reverie 5.gif" "81_4.gif"
if exist "..\Ghoyus Reverie 6.gif" ren "..\Ghoyus Reverie 6.gif" "81_5.gif"
if exist "..\Ghoyus Reverie 7.gif" ren "..\Ghoyus Reverie 7.gif" "81_6.gif"
if exist "..\Ghoyus Reverie 8.gif" ren "..\Ghoyus Reverie 8.gif" "81_7.gif"
if exist "..\Ghoyus Reverie 9.gif" ren "..\Ghoyus Reverie 9.gif" "81_8.gif"
if exist "..\Giddeus 1.gif" ren "..\Giddeus 1.gif" "91_0.gif"
if exist "..\Giddeus 2.gif" ren "..\Giddeus 2.gif" "91_1.gif"
if exist "..\Grand Palace of Hu'Xzoi 1.gif" ren "..\Grand Palace of Hu'Xzoi 1.gif" "22_0.gif"
if exist "..\Grand Palace of Hu'Xzoi 2.gif" ren "..\Grand Palace of Hu'Xzoi 2.gif" "22_1.gif"
if exist "..\Grand Palace of Hu'Xzoi 3.gif" ren "..\Grand Palace of Hu'Xzoi 3.gif" "22_2.gif"
if exist "..\Grauberg.gif" ren "..\Grauberg.gif" "59_0.gif"
if exist "..\Gusgen Mines 1.gif" ren "..\Gusgen Mines 1.gif" "c4_0.gif"
if exist "..\Gusgen Mines 2 a.gif" ren "..\Gusgen Mines 2 a.gif" "c4_1.gif"
if exist "..\Gusgen Mines 2 b.gif" ren "..\Gusgen Mines 2 b.gif" "c4_4.gif"
if exist "..\Gusgen Mines 3.gif" ren "..\Gusgen Mines 3.gif" "c4_2.gif"
if exist "..\Gusgen Mines 4.gif" ren "..\Gusgen Mines 4.gif" "c4_3.gif"
if exist "..\Gustav Tunnel 1.gif" ren "..\Gustav Tunnel 1.gif" "d4_0.gif"
if exist "..\Gustav Tunnel 2.gif" ren "..\Gustav Tunnel 2.gif" "d4_1.gif"
if exist "..\Hall of the Gods.gif" ren "..\Hall of the Gods.gif" "fb_0.gif"
if exist "..\Hall of Transference 1.gif" ren "..\Hall of Transference 1.gif" "0e_0.gif"
if exist "..\Hall of Transference 2.gif" ren "..\Hall of Transference 2.gif" "0e_1.gif"
if exist "..\Hall of Transference 3.gif" ren "..\Hall of Transference 3.gif" "0e_2.gif"
if exist "..\Halvung 1.gif" ren "..\Halvung 1.gif" "3e_0.gif"
if exist "..\Halvung 2.gif" ren "..\Halvung 2.gif" "3e_1.gif"
if exist "..\Halvung 3.gif" ren "..\Halvung 3.gif" "3e_2.gif"
if exist "..\Halvung 4.gif" ren "..\Halvung 4.gif" "3e_3.gif"
if exist "..\Heavens Tower 1.gif" ren "..\Heavens Tower 1.gif" "f2_0.gif"
if exist "..\Heavens Tower 2.gif" ren "..\Heavens Tower 2.gif" "f2_1.gif"
if exist "..\Heavens Tower 3.gif" ren "..\Heavens Tower 3.gif" "f2_2.gif"
if exist "..\Heavens Tower 4.gif" ren "..\Heavens Tower 4.gif" "f2_3.gif"
if exist "..\Horlais Peak.gif" ren "..\Horlais Peak.gif" "8b_0.gif"
if exist "..\Horutoto Ruins 1.gif" ren "..\Horutoto Ruins 1.gif" "c0_0.gif"
if exist "..\Horutoto Ruins 2.gif" ren "..\Horutoto Ruins 2.gif" "c0_1.gif"
if exist "..\Horutoto Ruins 3.gif" ren "..\Horutoto Ruins 3.gif" "c0_2.gif"
if exist "..\Horutoto Ruins 4.gif" ren "..\Horutoto Ruins 4.gif" "c0_3.gif"
if exist "..\Horutoto Ruins 5.gif" ren "..\Horutoto Ruins 5.gif" "c2_0.gif"
if exist "..\Horutoto Ruins 6.gif" ren "..\Horutoto Ruins 6.gif" "c2_1.gif"
if exist "..\Horutoto Ruins 7.gif" ren "..\Horutoto Ruins 7.gif" "c2_2.gif"
if exist "..\Horutoto Ruins 8.gif" ren "..\Horutoto Ruins 8.gif" "c2_3.gif"
if exist "..\Horutoto Ruins 9 a.gif" ren "..\Horutoto Ruins 9 a.gif" "c2_4.gif"
if exist "..\Horutoto Ruins 9 b.gif" ren "..\Horutoto Ruins 9 b.gif" "c2_5.gif"
if exist "..\Ifrit's Cauldron 1.gif" ren "..\Ifrit's Cauldron 1.gif" "cd_0.gif"
if exist "..\Ifrit's Cauldron 2.gif" ren "..\Ifrit's Cauldron 2.gif" "cd_1.gif"
if exist "..\Ifrit's Cauldron 3.gif" ren "..\Ifrit's Cauldron 3.gif" "cd_2.gif"
if exist "..\Ifrit's Cauldron 4.gif" ren "..\Ifrit's Cauldron 4.gif" "cd_3.gif"
if exist "..\Ifrit's Cauldron 5.gif" ren "..\Ifrit's Cauldron 5.gif" "cd_4.gif"
if exist "..\Ifrit's Cauldron 6.gif" ren "..\Ifrit's Cauldron 6.gif" "cd_5.gif"
if exist "..\Ifrit's Cauldron 7.gif" ren "..\Ifrit's Cauldron 7.gif" "cd_6.gif"
if exist "..\Ifrit's Cauldron 8.gif" ren "..\Ifrit's Cauldron 8.gif" "cd_7.gif"
if exist "..\Ilrusi Atoll 1.gif" ren "..\Ilrusi Atoll 1.gif" "37_0.gif"
if exist "..\Ilrusi Atoll 10.gif" ren "..\Ilrusi Atoll 10.gif" "37_9.gif"
if exist "..\Ilrusi Atoll 2.gif" ren "..\Ilrusi Atoll 2.gif" "37_1.gif"
if exist "..\Ilrusi Atoll 3.gif" ren "..\Ilrusi Atoll 3.gif" "37_2.gif"
if exist "..\Ilrusi Atoll 4.gif" ren "..\Ilrusi Atoll 4.gif" "37_3.gif"
if exist "..\Ilrusi Atoll 5.gif" ren "..\Ilrusi Atoll 5.gif" "37_4.gif"
if exist "..\Ilrusi Atoll 6.gif" ren "..\Ilrusi Atoll 6.gif" "37_5.gif"
if exist "..\Ilrusi Atoll 7.gif" ren "..\Ilrusi Atoll 7.gif" "37_6.gif"
if exist "..\Ilrusi Atoll 8.gif" ren "..\Ilrusi Atoll 8.gif" "37_7.gif"
if exist "..\Ilrusi Atoll 9.gif" ren "..\Ilrusi Atoll 9.gif" "37_8.gif"
if exist "..\Jade Sepulcher.gif" ren "..\Jade Sepulcher.gif" "43_0.gif"
if exist "..\Jeuno Residential Area.gif" ren "..\Jeuno Residential Area.gif" "d7_0.gif"
if exist "..\Jugner Forest [S].gif" ren "..\Jugner Forest [S].gif" "52_0.gif"
if exist "..\Jugner Forest.gif" ren "..\Jugner Forest.gif" "68_0.gif"
if exist "..\Kazham.gif" ren "..\Kazham.gif" "fa_0.gif"
if exist "..\King Ranperre's Tomb 1.gif" ren "..\King Ranperre's Tomb 1.gif" "be_0.gif"
if exist "..\King Ranperre's Tomb 2.gif" ren "..\King Ranperre's Tomb 2.gif" "be_1.gif"
if exist "..\Konschtat Highlands [A].gif" ren "..\Konschtat Highlands [A].gif" "0f_0.gif"
if exist "..\Konschtat Highlands.gif" ren "..\Konschtat Highlands.gif" "6c_0.gif"
if exist "..\Korroloka Tunnel 1.gif" ren "..\Korroloka Tunnel 1.gif" "ad_0.gif"
if exist "..\Korroloka Tunnel 2.gif" ren "..\Korroloka Tunnel 2.gif" "ad_1.gif"
if exist "..\Korroloka Tunnel 3.gif" ren "..\Korroloka Tunnel 3.gif" "ad_2.gif"
if exist "..\Korroloka Tunnel 4.gif" ren "..\Korroloka Tunnel 4.gif" "ad_3.gif"
if exist "..\Korroloka Tunnel 5.gif" ren "..\Korroloka Tunnel 5.gif" "ad_4.gif"
if exist "..\Kuftal Tunnel 1.gif" ren "..\Kuftal Tunnel 1.gif" "ae_0.gif"
if exist "..\Kuftal Tunnel 2.gif" ren "..\Kuftal Tunnel 2.gif" "ae_1.gif"
if exist "..\Kuftal Tunnel 3.gif" ren "..\Kuftal Tunnel 3.gif" "ae_2.gif"
if exist "..\Kuftal Tunnel 4.gif" ren "..\Kuftal Tunnel 4.gif" "ae_3.gif"
if exist "..\La Theine Plateau [A].gif" ren "..\La Theine Plateau [A].gif" "84_0.gif"
if exist "..\La Theine Plateau.gif" ren "..\La Theine Plateau.gif" "66_0.gif"
if exist "..\Labyrinth of Onzozo.gif" ren "..\Labyrinth of Onzozo.gif" "d5_0.gif"
if exist "..\La'Loff Amphitheater.gif" ren "..\La'Loff Amphitheater.gif" "b4_0.gif"
if exist "..\Lebros Cavern 1.gif" ren "..\Lebros Cavern 1.gif" "3f_0.gif"
if exist "..\Lebros Cavern 10.gif" ren "..\Lebros Cavern 10.gif" "3f_9.gif"
if exist "..\Lebros Cavern 2.gif" ren "..\Lebros Cavern 2.gif" "3f_1.gif"
if exist "..\Lebros Cavern 3.gif" ren "..\Lebros Cavern 3.gif" "3f_2.gif"
if exist "..\Lebros Cavern 4.gif" ren "..\Lebros Cavern 4.gif" "3f_3.gif"
if exist "..\Lebros Cavern 5.gif" ren "..\Lebros Cavern 5.gif" "3f_4.gif"
if exist "..\Lebros Cavern 6.gif" ren "..\Lebros Cavern 6.gif" "3f_5.gif"
if exist "..\Lebros Cavern 7.gif" ren "..\Lebros Cavern 7.gif" "3f_6.gif"
if exist "..\Lebros Cavern 8.gif" ren "..\Lebros Cavern 8.gif" "3f_7.gif"
if exist "..\Lebros Cavern 9.gif" ren "..\Lebros Cavern 9.gif" "3f_8.gif"
if exist "..\Leujaoam Sanctum 1.gif" ren "..\Leujaoam Sanctum 1.gif" "45_0.gif"
if exist "..\Leujaoam Sanctum 10.gif" ren "..\Leujaoam Sanctum 10.gif" "45_9.gif"
if exist "..\Leujaoam Sanctum 2.gif" ren "..\Leujaoam Sanctum 2.gif" "45_1.gif"
if exist "..\Leujaoam Sanctum 3.gif" ren "..\Leujaoam Sanctum 3.gif" "45_2.gif"
if exist "..\Leujaoam Sanctum 4.gif" ren "..\Leujaoam Sanctum 4.gif" "45_3.gif"
if exist "..\Leujaoam Sanctum 5.gif" ren "..\Leujaoam Sanctum 5.gif" "45_4.gif"
if exist "..\Leujaoam Sanctum 6.gif" ren "..\Leujaoam Sanctum 6.gif" "45_5.gif"
if exist "..\Leujaoam Sanctum 7.gif" ren "..\Leujaoam Sanctum 7.gif" "45_6.gif"
if exist "..\Leujaoam Sanctum 8.gif" ren "..\Leujaoam Sanctum 8.gif" "45_7.gif"
if exist "..\Leujaoam Sanctum 9.gif" ren "..\Leujaoam Sanctum 9.gif" "45_8.gif"
if exist "..\Lower Jeuno.gif" ren "..\Lower Jeuno.gif" "f5_0.gif"
if exist "..\Lufaise Meadows.gif" ren "..\Lufaise Meadows.gif" "18_0.gif"
if exist "..\Mamook 1.gif" ren "..\Mamook 1.gif" "41_0.gif"
if exist "..\Mamook 2.gif" ren "..\Mamook 2.gif" "41_1.gif"
if exist "..\Mamook 3.gif" ren "..\Mamook 3.gif" "41_2.gif"
if exist "..\Mamool Ja Training Grounds 1.gif" ren "..\Mamool Ja Training Grounds 1.gif" "42_0.gif"
if exist "..\Mamool Ja Training Grounds 10.gif" ren "..\Mamool Ja Training Grounds 10.gif" "42_9.gif"
if exist "..\Mamool Ja Training Grounds 2.gif" ren "..\Mamool Ja Training Grounds 2.gif" "42_1.gif"
if exist "..\Mamool Ja Training Grounds 3.gif" ren "..\Mamool Ja Training Grounds 3.gif" "42_2.gif"
if exist "..\Mamool Ja Training Grounds 4.gif" ren "..\Mamool Ja Training Grounds 4.gif" "42_3.gif"
if exist "..\Mamool Ja Training Grounds 5.gif" ren "..\Mamool Ja Training Grounds 5.gif" "42_4.gif"
if exist "..\Mamool Ja Training Grounds 6.gif" ren "..\Mamool Ja Training Grounds 6.gif" "42_5.gif"
if exist "..\Mamool Ja Training Grounds 7.gif" ren "..\Mamool Ja Training Grounds 7.gif" "42_6.gif"
if exist "..\Mamool Ja Training Grounds 8.gif" ren "..\Mamool Ja Training Grounds 8.gif" "42_7.gif"
if exist "..\Mamool Ja Training Grounds 9.gif" ren "..\Mamool Ja Training Grounds 9.gif" "42_8.gif"
if exist "..\Manaclipper.gif" ren "..\Manaclipper.gif" "03_0.gif"
if exist "..\Maze of Shakhrami 1.gif" ren "..\Maze of Shakhrami 1.gif" "c6_0.gif"
if exist "..\Maze of Shakhrami 2.gif" ren "..\Maze of Shakhrami 2.gif" "c6_1.gif"
if exist "..\Maze of Shakhrami Unknown.gif" ren "..\Maze of Shakhrami Unknown.gif" "c6_2.gif"
if exist "..\Meriphataud Mountains [S].gif" ren "..\Meriphataud Mountains [S].gif" "61_0.gif"
if exist "..\Meriphataud Mountains.gif" ren "..\Meriphataud Mountains.gif" "77_0.gif"
if exist "..\Metalworks.gif" ren "..\Metalworks.gif" "ed_0.gif"
if exist "..\Mhaura.gif" ren "..\Mhaura.gif" "f9_0.gif"
if exist "..\Mine Shaft #2716.gif" ren "..\Mine Shaft #2716.gif" "0d_0.gif"
if exist "..\Misareaux Coast.gif" ren "..\Misareaux Coast.gif" "19_0.gif"
if exist "..\Monarch Linn.gif" ren "..\Monarch Linn.gif" "1f_0.gif"
if exist "..\Monastic Cavern.gif" ren "..\Monastic Cavern.gif" "96_0.gif"
if exist "..\Mordion Gaol.gif" ren "..\Mordion Gaol.gif" "83_0.gif"
if exist "..\Mount Zhayolm.gif" ren "..\Mount Zhayolm.gif" "3d_0.gif"
if exist "..\Nashmau.gif" ren "..\Nashmau.gif" "35_0.gif"
if exist "..\Newton Movalpolos.gif" ren "..\Newton Movalpolos.gif" "0c_0.gif"
if exist "..\Norg.gif" ren "..\Norg.gif" "fc_0.gif"
if exist "..\North Gustaberg [S].gif" ren "..\North Gustaberg [S].gif" "58_0.gif"
if exist "..\North Gustaberg.gif" ren "..\North Gustaberg.gif" "6a_0.gif"
if exist "..\Northern San d'Oria.gif" ren "..\Northern San d'Oria.gif" "e7_0.gif"
if exist "..\Nyzul Isle 1.gif" ren "..\Nyzul Isle 1.gif" "4d_0.gif"
if exist "..\Nyzul Isle 2.gif" ren "..\Nyzul Isle 2.gif" "4d_1.gif"
if exist "..\Nyzul Isle 3.gif" ren "..\Nyzul Isle 3.gif" "4d_2.gif"
if exist "..\Nyzul Isle 4.gif" ren "..\Nyzul Isle 4.gif" "4d_3.gif"
if exist "..\Nyzul Isle 5.gif" ren "..\Nyzul Isle 5.gif" "4d_4.gif"
if exist "..\Nyzul Isle 6.gif" ren "..\Nyzul Isle 6.gif" "4d_5.gif"
if exist "..\Nyzul Isle 7.gif" ren "..\Nyzul Isle 7.gif" "4d_6.gif"
if exist "..\Nyzul Isle 8.gif" ren "..\Nyzul Isle 8.gif" "4d_7.gif"
if exist "..\Oldton Movalpolos.gif" ren "..\Oldton Movalpolos.gif" "0b_0.gif"
if exist "..\Ordelle's Caves 1 a.gif" ren "..\Ordelle's Caves 1 a.gif" "c1_0.gif"
if exist "..\Ordelle's Caves 1 b.gif" ren "..\Ordelle's Caves 1 b.gif" "c1_3.gif"
if exist "..\Ordelle's Caves 2.gif" ren "..\Ordelle's Caves 2.gif" "c1_1.gif"
if exist "..\Ordelle's Caves 3.gif" ren "..\Ordelle's Caves 3.gif" "c1_2.gif"
if exist "..\Palborough Mines 1.gif" ren "..\Palborough Mines 1.gif" "8f_0.gif"
if exist "..\Palborough Mines 2.gif" ren "..\Palborough Mines 2.gif" "8f_1.gif"
if exist "..\Palborough Mines 3.gif" ren "..\Palborough Mines 3.gif" "8f_2.gif"
if exist "..\Pashhow Marshlands [S].gif" ren "..\Pashhow Marshlands [S].gif" "5a_0.gif"
if exist "..\Pashhow Marshlands.gif" ren "..\Pashhow Marshlands.gif" "6d_0.gif"
if exist "..\Periqia 1.gif" ren "..\Periqia 1.gif" "38_0.gif"
if exist "..\Periqia 10.gif" ren "..\Periqia 10.gif" "38_9.gif"
if exist "..\Periqia 2.gif" ren "..\Periqia 2.gif" "38_1.gif"
if exist "..\Periqia 3.gif" ren "..\Periqia 3.gif" "38_2.gif"
if exist "..\Periqia 4.gif" ren "..\Periqia 4.gif" "38_3.gif"
if exist "..\Periqia 5.gif" ren "..\Periqia 5.gif" "38_4.gif"
if exist "..\Periqia 6.gif" ren "..\Periqia 6.gif" "38_5.gif"
if exist "..\Periqia 7.gif" ren "..\Periqia 7.gif" "38_6.gif"
if exist "..\Periqia 8.gif" ren "..\Periqia 8.gif" "38_7.gif"
if exist "..\Periqia 9.gif" ren "..\Periqia 9.gif" "38_8.gif"
if exist "..\Phanauet Channel.gif" ren "..\Phanauet Channel.gif" "01_0.gif"
if exist "..\Phomiuna Aqueducts 1.gif" ren "..\Phomiuna Aqueducts 1.gif" "1b_0.gif"
if exist "..\Phomiuna Aqueducts 2.gif" ren "..\Phomiuna Aqueducts 2.gif" "1b_1.gif"
if exist "..\Phomiuna Aqueducts 3.gif" ren "..\Phomiuna Aqueducts 3.gif" "1b_2.gif"
if exist "..\Port Bastok.gif" ren "..\Port Bastok.gif" "ec_0.gif"
if exist "..\Port Jeuno.gif" ren "..\Port Jeuno.gif" "f6_0.gif"
if exist "..\Port San d'Oria.gif" ren "..\Port San d'Oria.gif" "e8_0.gif"
if exist "..\Port Windurst.gif" ren "..\Port Windurst.gif" "f0_0.gif"
if exist "..\Promyvion - Dem.gif" ren "..\Promyvion - Dem.gif" "12_0.gif"
if exist "..\Promyvion - Holla.gif" ren "..\Promyvion - Holla.gif" "10_0.gif"
if exist "..\Promyvion - Mea.gif" ren "..\Promyvion - Mea.gif" "14_0.gif"
if exist "..\Promyvion - Vahzl.gif" ren "..\Promyvion - Vahzl.gif" "16_0.gif"
if exist "..\Pso'Xja 1.gif" ren "..\Pso'Xja 1.gif" "09_0.gif"
if exist "..\Pso'Xja 10.gif" ren "..\Pso'Xja 10.gif" "09_9.gif"
if exist "..\Pso'Xja 11.gif" ren "..\Pso'Xja 11.gif" "09_10.gif"
if exist "..\Pso'Xja 12.gif" ren "..\Pso'Xja 12.gif" "09_11.gif"
if exist "..\Pso'Xja 13.gif" ren "..\Pso'Xja 13.gif" "09_12.gif"
if exist "..\Pso'Xja 14.gif" ren "..\Pso'Xja 14.gif" "09_13.gif"
if exist "..\Pso'Xja 15.gif" ren "..\Pso'Xja 15.gif" "09_14.gif"
if exist "..\Pso'Xja 16.gif" ren "..\Pso'Xja 16.gif" "09_15.gif"
if exist "..\Pso'Xja 17.gif" ren "..\Pso'Xja 17.gif" "09_16.gif"
if exist "..\Pso'Xja 18.gif" ren "..\Pso'Xja 18.gif" "09_17.gif"
if exist "..\Pso'Xja 19.gif" ren "..\Pso'Xja 19.gif" "09_18.gif"
if exist "..\Pso'Xja 2.gif" ren "..\Pso'Xja 2.gif" "09_1.gif"
if exist "..\Pso'Xja 20.gif" ren "..\Pso'Xja 20.gif" "09_19.gif"
if exist "..\Pso'Xja 21.gif" ren "..\Pso'Xja 21.gif" "09_20.gif"
if exist "..\Pso'Xja 3.gif" ren "..\Pso'Xja 3.gif" "09_2.gif"
if exist "..\Pso'Xja 4.gif" ren "..\Pso'Xja 4.gif" "09_3.gif"
if exist "..\Pso'Xja 5.gif" ren "..\Pso'Xja 5.gif" "09_4.gif"
if exist "..\Pso'Xja 6.gif" ren "..\Pso'Xja 6.gif" "09_5.gif"
if exist "..\Pso'Xja 7.gif" ren "..\Pso'Xja 7.gif" "09_6.gif"
if exist "..\Pso'Xja 8.gif" ren "..\Pso'Xja 8.gif" "09_7.gif"
if exist "..\Pso'Xja 9.gif" ren "..\Pso'Xja 9.gif" "09_8.gif"
if exist "..\Purgonorgo Isle.gif" ren "..\Purgonorgo Isle.gif" "04_1.gif"
if exist "..\Qu'Bia Arena.gif" ren "..\Qu'Bia Arena.gif" "ce_0.gif"
if exist "..\Qufim Island.gif" ren "..\Qufim Island.gif" "7e_0.gif"
if exist "..\Quicksand Caves 1.gif" ren "..\Quicksand Caves 1.gif" "d0_0.gif"
if exist "..\Quicksand Caves 2.gif" ren "..\Quicksand Caves 2.gif" "d0_1.gif"
if exist "..\Quicksand Caves 3.gif" ren "..\Quicksand Caves 3.gif" "d0_2.gif"
if exist "..\Quicksand Caves 4.gif" ren "..\Quicksand Caves 4.gif" "d0_3.gif"
if exist "..\Quicksand Caves 5.gif" ren "..\Quicksand Caves 5.gif" "d0_4.gif"
if exist "..\Quicksand Caves 6.gif" ren "..\Quicksand Caves 6.gif" "d0_5.gif"
if exist "..\Quicksand Caves 7.gif" ren "..\Quicksand Caves 7.gif" "d0_6.gif"
if exist "..\Quicksand Caves 8.gif" ren "..\Quicksand Caves 8.gif" "d0_7.gif"
if exist "..\Qulun Dome.gif" ren "..\Qulun Dome.gif" "94_0.gif"
if exist "..\Rabao.gif" ren "..\Rabao.gif" "f7_0.gif"
if exist "..\Ranguemont Pass.gif" ren "..\Ranguemont Pass.gif" "a6_0.gif"
if exist "..\Riverne - Site #A01 a.gif" ren "..\Riverne - Site #A01 a.gif" "1e_0.gif"
if exist "..\Riverne - Site #A01 b.gif" ren "..\Riverne - Site #A01 b.gif" "1e_1.gif"
if exist "..\Riverne - Site #B01 a.gif" ren "..\Riverne - Site #B01 a.gif" "1d_0.gif"
if exist "..\Riverne - Site #B01 b.gif" ren "..\Riverne - Site #B01 b.gif" "1d_1.gif"
if exist "..\Rolanberry Fields [S].gif" ren "..\Rolanberry Fields [S].gif" "5b_0.gif"
if exist "..\Rolanberry Fields.gif" ren "..\Rolanberry Fields.gif" "6e_0.gif"
if exist "..\Ro'Maeve.gif" ren "..\Ro'Maeve.gif" "7a_0.gif"
if exist "..\Ru'Aun Gardens.gif" ren "..\Ru'Aun Gardens.gif" "82_0.gif"
if exist "..\Ru'Lude Gardens.gif" ren "..\Ru'Lude Gardens.gif" "f3_0.gif"
if exist "..\Ruthotz Silvermines 1.gif" ren "..\Ruthotz Silvermines 1.gif" "5d_0.gif"
if exist "..\Ruthotz Silvermines 10.gif" ren "..\Ruthotz Silvermines 10.gif" "5d_9.gif"
if exist "..\Ruthotz Silvermines 11.gif" ren "..\Ruthotz Silvermines 11.gif" "5d_10.gif"
if exist "..\Ruthotz Silvermines 12.gif" ren "..\Ruthotz Silvermines 12.gif" "5d_11.gif"
if exist "..\Ruthotz Silvermines 13.gif" ren "..\Ruthotz Silvermines 13.gif" "5d_12.gif"
if exist "..\Ruthotz Silvermines 14.gif" ren "..\Ruthotz Silvermines 14.gif" "5d_13.gif"
if exist "..\Ruthotz Silvermines 15.gif" ren "..\Ruthotz Silvermines 15.gif" "5d_14.gif"
if exist "..\Ruthotz Silvermines 16.gif" ren "..\Ruthotz Silvermines 16.gif" "5d_15.gif"
if exist "..\Ruthotz Silvermines 17.gif" ren "..\Ruthotz Silvermines 17.gif" "5d_16.gif"
if exist "..\Ruthotz Silvermines 18.gif" ren "..\Ruthotz Silvermines 18.gif" "5d_17.gif"
if exist "..\Ruthotz Silvermines 2.gif" ren "..\Ruthotz Silvermines 2.gif" "5d_1.gif"
if exist "..\Ruthotz Silvermines 3.gif" ren "..\Ruthotz Silvermines 3.gif" "5d_2.gif"
if exist "..\Ruthotz Silvermines 4.gif" ren "..\Ruthotz Silvermines 4.gif" "5d_3.gif"
if exist "..\Ruthotz Silvermines 5.gif" ren "..\Ruthotz Silvermines 5.gif" "5d_4.gif"
if exist "..\Ruthotz Silvermines 6.gif" ren "..\Ruthotz Silvermines 6.gif" "5d_5.gif"
if exist "..\Ruthotz Silvermines 7.gif" ren "..\Ruthotz Silvermines 7.gif" "5d_6.gif"
if exist "..\Ruthotz Silvermines 8.gif" ren "..\Ruthotz Silvermines 8.gif" "5d_7.gif"
if exist "..\Ruthotz Silvermines 9.gif" ren "..\Ruthotz Silvermines 9.gif" "5d_8.gif"
if exist "..\Sacrarium 1.gif" ren "..\Sacrarium 1.gif" "1c_0.gif"
if exist "..\Sacrarium 2.gif" ren "..\Sacrarium 2.gif" "1c_1.gif"
if exist "..\Sacrificial Chamber.gif" ren "..\Sacrificial Chamber.gif" "a3_0.gif"
if exist "..\San d'Oria Residential Area.gif" ren "..\San d'Oria Residential Area.gif" "d8_0.gif"
if exist "..\Sauromugue Champaign [S].gif" ren "..\Sauromugue Champaign [S].gif" "62_0.gif"
if exist "..\Sauromugue Champaign.gif" ren "..\Sauromugue Champaign.gif" "78_0.gif"
if exist "..\Sea Serpent Grotto 1.gif" ren "..\Sea Serpent Grotto 1.gif" "b0_0.gif"
if exist "..\Sea Serpent Grotto 2.gif" ren "..\Sea Serpent Grotto 2.gif" "b0_1.gif"
if exist "..\Sea Serpent Grotto 3.gif" ren "..\Sea Serpent Grotto 3.gif" "b0_2.gif"
if exist "..\Sea Serpent Grotto 4.gif" ren "..\Sea Serpent Grotto 4.gif" "b0_3.gif"
if exist "..\Sea Serpent Grotto 5.gif" ren "..\Sea Serpent Grotto 5.gif" "b0_4.gif"
if exist "..\Sealion's Den.gif" ren "..\Sealion's Den.gif" "20_0.gif"
if exist "..\Selbina.gif" ren "..\Selbina.gif" "f8_0.gif"
if exist "..\Silver Sea Remnants 1.gif" ren "..\Silver Sea Remnants 1.gif" "4c_0.gif"
if exist "..\Silver Sea Remnants 2.gif" ren "..\Silver Sea Remnants 2.gif" "4c_1.gif"
if exist "..\Silver Sea Remnants 3.gif" ren "..\Silver Sea Remnants 3.gif" "4c_2.gif"
if exist "..\Silver Sea Remnants 4.gif" ren "..\Silver Sea Remnants 4.gif" "4c_3.gif"
if exist "..\Silver Sea Remnants 5.gif" ren "..\Silver Sea Remnants 5.gif" "4c_4.gif"
if exist "..\South Gustaberg.gif" ren "..\South Gustaberg.gif" "6b_0.gif"
if exist "..\Southern San d'Oria [S].gif" ren "..\Southern San d'Oria [S].gif" "50_0.gif"
if exist "..\Southern San d'Oria.gif" ren "..\Southern San d'Oria.gif" "e6_0.gif"
if exist "..\Spire of Dem.gif" ren "..\Spire of Dem.gif" "13_0.gif"
if exist "..\Spire of Holla.gif" ren "..\Spire of Holla.gif" "11_0.gif"
if exist "..\Spire of Mea.gif" ren "..\Spire of Mea.gif" "15_0.gif"
if exist "..\Spire of Vahzl.gif" ren "..\Spire of Vahzl.gif" "17_0.gif"
if exist "..\Stellar Fulcrum.gif" ren "..\Stellar Fulcrum.gif" "b3_0.gif"
if exist "..\Tahrongi Canyon [A].gif" ren "..\Tahrongi Canyon [A].gif" "2d_0.gif"
if exist "..\Tahrongi Canyon.gif" ren "..\Tahrongi Canyon.gif" "75_0.gif"
if exist "..\Talacca Cove.gif" ren "..\Talacca Cove.gif" "39_0.gif"
if exist "..\Tavnazian Safehold 1.gif" ren "..\Tavnazian Safehold 1.gif" "1a_0.gif"
if exist "..\Tavnazian Safehold 2.gif" ren "..\Tavnazian Safehold 2.gif" "1a_1.gif"
if exist "..\Tavnazian Safehold 3.gif" ren "..\Tavnazian Safehold 3.gif" "1a_2.gif"
if exist "..\Temenos-C1.gif" ren "..\Temenos-C1.gif" "25_21.gif"
if exist "..\Temenos-C2.gif" ren "..\Temenos-C2.gif" "25_22.gif"
if exist "..\Temenos-C3.gif" ren "..\Temenos-C3.gif" "25_23.gif"
if exist "..\Temenos-C4.gif" ren "..\Temenos-C4.gif" "25_24.gif"
if exist "..\Temenos-CB1.gif" ren "..\Temenos-CB1.gif" "25_25.gif"
if exist "..\Temenos-E1.gif" ren "..\Temenos-E1.gif" "25_7.gif"
if exist "..\Temenos-E2.gif" ren "..\Temenos-E2.gif" "25_8.gif"
if exist "..\Temenos-E3.gif" ren "..\Temenos-E3.gif" "25_9.gif"
if exist "..\Temenos-E4.gif" ren "..\Temenos-E4.gif" "25_10.gif"
if exist "..\Temenos-E5.gif" ren "..\Temenos-E5.gif" "25_11.gif"
if exist "..\Temenos-E6.gif" ren "..\Temenos-E6.gif" "25_12.gif"
if exist "..\Temenos-E7.gif" ren "..\Temenos-E7.gif" "25_13.gif"
if exist "..\Temenos-Entrance.gif" ren "..\Temenos-Entrance.gif" "25_26.gif"
if exist "..\Temenos-N1.gif" ren "..\Temenos-N1.gif" "25_0.gif"
if exist "..\Temenos-N2.gif" ren "..\Temenos-N2.gif" "25_1.gif"
if exist "..\Temenos-N3.gif" ren "..\Temenos-N3.gif" "25_2.gif"
if exist "..\Temenos-N4.gif" ren "..\Temenos-N4.gif" "25_3.gif"
if exist "..\Temenos-N5.gif" ren "..\Temenos-N5.gif" "25_4.gif"
if exist "..\Temenos-N6.gif" ren "..\Temenos-N6.gif" "25_5.gif"
if exist "..\Temenos-N7.gif" ren "..\Temenos-N7.gif" "25_6.gif"
if exist "..\Temenos-W1.gif" ren "..\Temenos-W1.gif" "25_14.gif"
if exist "..\Temenos-W2.gif" ren "..\Temenos-W2.gif" "25_15.gif"
if exist "..\Temenos-W3.gif" ren "..\Temenos-W3.gif" "25_16.gif"
if exist "..\Temenos-W4.gif" ren "..\Temenos-W4.gif" "25_17.gif"
if exist "..\Temenos-W5.gif" ren "..\Temenos-W5.gif" "25_18.gif"
if exist "..\Temenos-W6.gif" ren "..\Temenos-W6.gif" "25_19.gif"
if exist "..\Temenos-W7.gif" ren "..\Temenos-W7.gif" "25_20.gif"
if exist "..\Temple of Uggalepih 1.gif" ren "..\Temple of Uggalepih 1.gif" "9f_0.gif"
if exist "..\Temple of Uggalepih 2.gif" ren "..\Temple of Uggalepih 2.gif" "9f_1.gif"
if exist "..\Temple of Uggalepih 3.gif" ren "..\Temple of Uggalepih 3.gif" "9f_2.gif"
if exist "..\Temple of Uggalepih 4.gif" ren "..\Temple of Uggalepih 4.gif" "9f_3.gif"
if exist "..\The Boyahda Tree 1.gif" ren "..\The Boyahda Tree 1.gif" "99_0.gif"
if exist "..\The Boyahda Tree 2.gif" ren "..\The Boyahda Tree 2.gif" "99_1.gif"
if exist "..\The Boyahda Tree 3.gif" ren "..\The Boyahda Tree 3.gif" "99_2.gif"
if exist "..\The Boyahda Tree 4.gif" ren "..\The Boyahda Tree 4.gif" "99_3.gif"
if exist "..\The Celestial Nexus.gif" ren "..\The Celestial Nexus.gif" "b5_0.gif"
if exist "..\The Colosseum 1.gif" ren "..\The Colosseum 1.gif" "47_0.gif"
if exist "..\The Colosseum 2.gif" ren "..\The Colosseum 2.gif" "47_1.gif"
if exist "..\The Eldieme Necropolis 1.gif" ren "..\The Eldieme Necropolis 1.gif" "c3_0.gif"
if exist "..\The Eldieme Necropolis 2.gif" ren "..\The Eldieme Necropolis 2.gif" "c3_1.gif"
if exist "..\The Eldieme Necropolis 3.gif" ren "..\The Eldieme Necropolis 3.gif" "c3_2.gif"
if exist "..\The Garden of Ru'Hmet 1.gif" ren "..\The Garden of Ru'Hmet 1.gif" "23_0.gif"
if exist "..\The Garden of Ru'Hmet 2.gif" ren "..\The Garden of Ru'Hmet 2.gif" "23_1.gif"
if exist "..\The Garden of Ru'Hmet 3.gif" ren "..\The Garden of Ru'Hmet 3.gif" "23_2.gif"
if exist "..\The Garden of Ru'Hmet 4.gif" ren "..\The Garden of Ru'Hmet 4.gif" "23_3.gif"
if exist "..\The Last Stand.gif" ren "..\The Last Stand.gif" "b7_0.gif"
if exist "..\The Sanctuary of Zi'Tah.gif" ren "..\The Sanctuary of Zi'Tah.gif" "79_0.gif"
if exist "..\The Shrine of Ru'Avitau 1.gif" ren "..\The Shrine of Ru'Avitau 1.gif" "b2_0.gif"
if exist "..\The Shrine of Ru'Avitau 2.gif" ren "..\The Shrine of Ru'Avitau 2.gif" "b2_1.gif"
if exist "..\The Shrine of Ru'Avitau 3.gif" ren "..\The Shrine of Ru'Avitau 3.gif" "b2_2.gif"
if exist "..\The Shrine of Ru'Avitau 4.gif" ren "..\The Shrine of Ru'Avitau 4.gif" "b2_3.gif"
if exist "..\The Shrine of Ru'Avitau 5.gif" ren "..\The Shrine of Ru'Avitau 5.gif" "b2_4.gif"
if exist "..\The Shrine of Ru'Avitau 6.gif" ren "..\The Shrine of Ru'Avitau 6.gif" "b2_5.gif"
if exist "..\The Shrouded Maw.gif" ren "..\The Shrouded Maw.gif" "0a_0.gif"
if exist "..\Throne Room.gif" ren "..\Throne Room.gif" "a5_0.gif"
if exist "..\Toraimarai Canal 1.gif" ren "..\Toraimarai Canal 1.gif" "a9_0.gif"
if exist "..\Toraimarai Canal 2.gif" ren "..\Toraimarai Canal 2.gif" "a9_1.gif"
if exist "..\Uleguerand Range.gif" ren "..\Uleguerand Range.gif" "05_0.gif"
if exist "..\Upper Jeuno.gif" ren "..\Upper Jeuno.gif" "f4_0.gif"
if exist "..\Valkurm Dunes.gif" ren "..\Valkurm Dunes.gif" "67_0.gif"
if exist "..\Valley of Sorrows.gif" ren "..\Valley of Sorrows.gif" "80_0.gif"
if exist "..\Ve'Lugannon Palace 1.gif" ren "..\Ve'Lugannon Palace 1.gif" "b1_0.gif"
if exist "..\Ve'Lugannon Palace 2.gif" ren "..\Ve'Lugannon Palace 2.gif" "b1_1.gif"
if exist "..\Ve'Lugannon Palace 3.gif" ren "..\Ve'Lugannon Palace 3.gif" "b1_2.gif"
if exist "..\Ve'Lugannon Palace 4.gif" ren "..\Ve'Lugannon Palace 4.gif" "b1_3.gif"
if exist "..\Ve'Lugannon Palace 5.gif" ren "..\Ve'Lugannon Palace 5.gif" "b1_4.gif"
if exist "..\Ve'Lugannon Palace 6.gif" ren "..\Ve'Lugannon Palace 6.gif" "b1_5.gif"
if exist "..\Ve'Lugannon Palace 7.gif" ren "..\Ve'Lugannon Palace 7.gif" "b1_6.gif"
if exist "..\Ve'Lugannon Palace 8.gif" ren "..\Ve'Lugannon Palace 8.gif" "b1_7.gif"
if exist "..\Ve'Lugannon Palace 9.gif" ren "..\Ve'Lugannon Palace 9.gif" "b1_8.gif"
if exist "..\Vunkerl Inlet.gif" ren "..\Vunkerl Inlet.gif" "53_0.gif"
if exist "..\Wajaom Woodlands.gif" ren "..\Wajaom Woodlands.gif" "33_0.gif"
if exist "..\Walk of Echoes.gif" ren "..\Walk of Echoes.gif" "b6_0.gif"
if exist "..\Waughroon Shrine.gif" ren "..\Waughroon Shrine.gif" "90_0.gif"
if exist "..\West Ronfaure.gif" ren "..\West Ronfaure.gif" "64_0.gif"
if exist "..\West Sarutabaruta.gif" ren "..\West Sarutabaruta.gif" "73_0.gif"
if exist "..\West Sarutaburuta [S].gif" ren "..\West Sarutaburuta [S].gif" "5f_0.gif"
if exist "..\Western Altepa Desert.gif" ren "..\Western Altepa Desert.gif" "7d_0.gif"
if exist "..\Windurst Residential Area.gif" ren "..\Windurst Residential Area.gif" "da_0.gif"
if exist "..\Windurst Walls.gif" ren "..\Windurst Walls.gif" "ef_0.gif"
if exist "..\Windurst Waters 1 [S].gif" ren "..\Windurst Waters 1 [S].gif" "5e_0.gif"
if exist "..\Windurst Waters 1.gif" ren "..\Windurst Waters 1.gif" "ee_0.gif"
if exist "..\Windurst Waters 2 [S].gif" ren "..\Windurst Waters 2 [S].gif" "5e_1.gif"
if exist "..\Windurst Waters 2.gif" ren "..\Windurst Waters 2.gif" "ee_1.gif"
if exist "..\Windurst Woods.gif" ren "..\Windurst Woods.gif" "f1_0.gif"
if exist "..\Xarcabard [S].gif" ren "..\Xarcabard [S].gif" "89_0.gif"
if exist "..\Xarcabard.gif" ren "..\Xarcabard.gif" "70_0.gif"
if exist "..\Yhoator Jungle.gif" ren "..\Yhoator Jungle.gif" "7c_0.gif"
if exist "..\Yughott Grotto 1.gif" ren "..\Yughott Grotto 1.gif" "8e_0.gif"
if exist "..\Yughott Grotto 2.gif" ren "..\Yughott Grotto 2.gif" "8e_1.gif"
if exist "..\Yuhtunga Jungle.gif" ren "..\Yuhtunga Jungle.gif" "7b_0.gif"
if exist "..\Zeruhn Mines.gif " ren "..\Zeruhn Mines.gif " "ac_0.gif"
if exist "..\Zhayolm Remnants 1.gif" ren "..\Zhayolm Remnants 1.gif" "49_0.gif"
if exist "..\Zhayolm Remnants 2.gif" ren "..\Zhayolm Remnants 2.gif" "49_1.gif"
if exist "..\Zhayolm Remnants 3.gif" ren "..\Zhayolm Remnants 3.gif" "49_2.gif"
if exist "..\Zhayolm Remnants 4.gif" ren "..\Zhayolm Remnants 4.gif" "49_3.gif"
if exist "..\Zhayolm Remnants 5.gif" ren "..\Zhayolm Remnants 5.gif" "49_4.gif"
if exist "..\Zhayolm Remnants 6.gif" ren "..\Zhayolm Remnants 6.gif" "49_5.gif"
if exist "..\Zhayolm Remnants 7.gif" ren "..\Zhayolm Remnants 7.gif" "49_6.gif"